/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountTheme" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface AccountTheme
{
    primaryColor?:string;
    secondaryColor?:string;
    foregroundColor?:string;
    backgroundColor?:string;
    borderColor?:string;
    borderWidth?:string;
    borderRadius?:string;
    messageContainerWidth?:string;
}
