/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountUpdateRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountLlmProperties } from './AccountLlmProperties';
import type { AccountTheme } from './AccountTheme';
import type { EmailAttributionEventType } from './EmailAttributionEventType';
import type { Currency } from './Currency';
import type { AccountType } from './AccountType';

export interface AccountUpdateRequest
{
    id:number;
    name?:string;
    description?:string;
    timezone?:string;
    industry?:string;
    mfaRequired?:boolean;
    minProfileSendIntervalMs?:number;
    messageSubjectPreviewPrefix?:string;
    placeEmailTrackingPixelAtBottom?:boolean;
    websiteUrl?:string;
    logoUrl?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    defaultSenderName?:string;
    defaultSenderEmail?:string;
    platformUsages?:string[];
    privacyPolicyUrl?:string;
    termsUrl?:string;
    minMessageSendIntervalHours?:number;
    messagePreviewPrefix?:string;
    autoUpgrade?:boolean;
    emailAttributionTime?:number;
    smsAttributionTime?:number;
    notificationAttributionTime?:number;
    notificationCompanyName?:string;
    notificationMinMessageSendIntervalHours?:number;
    notificationLogoUrl?:string;
    type?:AccountType;
    currency?:Currency;
    emailAttributionType?:EmailAttributionEventType;
    theme?:AccountTheme;
    llmProperties?:AccountLlmProperties;
}
