/* <ALLOW_AUTO_DELETE DEPENDENCIES="Account" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountLlmProperties } from './AccountLlmProperties';
import type { AccountTheme } from './AccountTheme';
import type { FormRecord } from './FormRecord';
import type { FileRecord } from './FileRecord';
import type { EmailAttributionEventType } from './EmailAttributionEventType';
import type { Currency } from './Currency';
import type { MessageRecord } from './MessageRecord';
import type { MessageSender } from './MessageSender';
import type { MessageTemplate } from './MessageTemplate';
import type { ApiKey } from './ApiKey';
import type { ProfileGroup } from './ProfileGroup';
import type { Profile } from './Profile';
import type { User } from './User';
import type { Location } from './Location';
import type { Region } from './Region';
import type { EventRecord } from './EventRecord';
import type { AccountType } from './AccountType';

/**
 * Client accounts
 */
export interface Account
{
    id:number;
    name:string;
    created?:number;
    description?:string;
    timezone:string;
    industry?:string;
    mfaRequired?:boolean;
    /**
     * The min number of milliseconds between
     * sending messages to a single profile
     * excluding transactional messages
     */
    minProfileSendIntervalMs?:number;
    messageSubjectPreviewPrefix?:string;
    placeEmailTrackingPixelAtBottom?:boolean;
    websiteUrl?:string;
    logoUrl?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    privacyPolicyUrl?:string;
    termsUrl?:string;
    emailAttributionTime?:number;
    smsAttributionTime?:number;
    notificationAttributionTime?:number;
    platformUsages?:string[];
    minMessageSendIntervalHours?:number;
    messagePreviewPrefix?:string;
    billingPeriod?:number;
    stripeCustomerId?:string;
    stripeSubscriptionId?:string;
    stripeSubscriptionActive?:boolean;
    formSubmissionEmail?:string;
    autoUpgrade?:boolean;
    hasUsedFreePlan?:boolean;
    notificationCompanyName?:string;
    notificationMinMessageSendIntervalHours?:number;
    notificationLogoUrl?:string;
    type?:AccountType;
    events?:EventRecord[];
    regions?:Region[];
    locations?:Location[];
    users?:User[];
    profiles?:Profile[];
    profileGroups?:ProfileGroup[];
    apiKeys?:ApiKey[];
    messageTemplates?:MessageTemplate[];
    messageSenders?:MessageSender[];
    messages?:MessageRecord[];
    currency:Currency;
    emailAttributionType?:EmailAttributionEventType;
    files?:FileRecord[];
    forms?:FormRecord[];
    theme?:AccountTheme;
    llmProperties?:AccountLlmProperties;
}
