/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountDomain" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface AccountDomain
{
    id:string;
    verified?:boolean;
    /**
     * Used with TXT records to verify domain ownership
     */
    verificationCode?:string;
    /**
     * Verification is not required for data collection
     * to be enabled.
     */
    dataCollectionEnabled?:boolean;
}
