/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const AccountTypeScheme=z.enum([
    "business",
    "enterprise",
]).describe("Default type is business\n */");
