/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "business",
    "enterprise"
] as const;
Object.freeze(unionAry);

/**
 * Default type is business
 */
export type AccountType=typeof unionAry[number];

/**
 * Default type is business
 */
export const allAccountTypeAry:AccountType[]=unionAry as any;
