/* <ALLOW_AUTO_DELETE DEPENDENCIES="Account" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { EmailAttributionEventType } from './EmailAttributionEventType';
import { Currency } from './Currency';
import { MessageDelivery } from './MessageDelivery';
import { MessageSender } from './MessageSender';
import { MessageTemplate } from './MessageTemplate';
import { ApiKey } from './ApiKey';
import { Profile } from './Profile';
import { User } from './User';
import { Location } from './Location';
import { Region } from './Region';
import { EventRecord } from './EventRecord';

/**
 * Client accounts
 */
export interface Account
{
    id:number;
    timezone:string;
    industry?:string;
    mfaRequired?:boolean;
    /**
     * The min number of milliseconds between
     * sending messages to a single profile
     * excluding transactional messages
     */
    minProfileSendIntervalMs?:number;
    messageSubjectPreviewPrefix?:string;
    placeEmailTrackingPixelAtBottom?:boolean;
    events?:EventRecord[];
    regions?:Region[];
    locations?:Location[];
    users?:User[];
    profiles?:Profile[];
    apiKeys?:ApiKey[];
    messageTemplates?:MessageTemplate[];
    messageSenders?:MessageSender[];
    messageDeliveries?:MessageDelivery[];
    currency:Currency;
    emailAttributionType?:EmailAttributionEventType;
}
