/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountTheme" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__AccountThemeScheme=z.object({
    primaryColor:z.string().max(255).optional(),
    secondaryColor:z.string().max(255).optional(),
    foregroundColor:z.string().max(255).optional(),
    backgroundColor:z.string().max(255).optional(),
    borderColor:z.string().max(255).optional(),
    borderWidth:z.string().max(255).optional(),
    borderRadius:z.string().max(255).optional(),
    messageContainerWidth:z.string().max(255).optional(),
});
const __lazy__AccountThemeScheme=z.object({
});
export const AccountThemeScheme:(typeof __base__AccountThemeScheme)=__base__AccountThemeScheme.merge(__lazy__AccountThemeScheme) as any;
