/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountLlmProperties" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__AccountLlmPropertiesScheme=z.object({
    defaultConvo:z.string().optional(),
    messageBuilderConvo:z.string().optional(),
});
const __lazy__AccountLlmPropertiesScheme=z.object({
});
export const AccountLlmPropertiesScheme:(typeof __base__AccountLlmPropertiesScheme)=__base__AccountLlmPropertiesScheme.merge(__lazy__AccountLlmPropertiesScheme) as any;
