/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountRegistrationData" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountScheme } from './AccountScheme';

const __base__AccountRegistrationDataScheme=z.object({
});
const __lazy__AccountRegistrationDataScheme=z.object({
    account:z.lazy(()=>AccountScheme),
});
export const AccountRegistrationDataScheme:(typeof __base__AccountRegistrationDataScheme)=__base__AccountRegistrationDataScheme.merge(__lazy__AccountRegistrationDataScheme) as any;
