/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountLlmProperties" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface AccountLlmProperties
{
    defaultConvo?:string;
    messageBuilderConvo?:string;
}
