/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountRegistration" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountRegistrationData } from './AccountRegistrationData';

export interface AccountRegistration
{
    id:number;
    created?:number;
    companyName:string;
    userName?:string;
    userEmail?:string;
    defaultSenderName?:string;
    defaultSenderEmail?:string;
    allowMarketingComms?:boolean;
    demoRequested?:number;
    data:AccountRegistrationData;
}
