/* <ALLOW_AUTO_DELETE DEPENDENCIES="AccountRegistration" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountRegistrationDataScheme } from './AccountRegistrationDataScheme';

const __base__AccountRegistrationScheme=z.object({
    id:z.number().int(),
    created:z.number().optional(),
    companyName:z.string().max(255),
    userName:z.string().max(255).optional(),
    userEmail:z.string().email().optional(),
    defaultSenderName:z.string().max(255).optional(),
    defaultSenderEmail:z.string().email().optional(),
    allowMarketingComms:z.boolean().optional(),
    demoRequested:z.number().optional(),
});
const __lazy__AccountRegistrationScheme=z.object({
    data:z.lazy(()=>AccountRegistrationDataScheme),
});
export const AccountRegistrationScheme:(typeof __base__AccountRegistrationScheme)=__base__AccountRegistrationScheme.merge(__lazy__AccountRegistrationScheme) as any;
