/* <ALLOW_AUTO_DELETE DEPENDENCIES="ActionRecord" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__ActionRecordScheme=z.object({
    name:z.string().max(255).describe("Name of the action and group.\nExample = FirstProductDiscount.default"),
    nodeAddress:z.string().max(255).describe("Address of the node storing workers"),
    trigger:z.string().max(255).describe("Address of the event that triggers the action.\nA triggers address is usually the same as its name."),
});
const __lazy__ActionRecordScheme=z.object({
});
export const ActionRecordScheme:(typeof __base__ActionRecordScheme)=__base__ActionRecordScheme.merge(__lazy__ActionRecordScheme) as any;
