/* <ALLOW_AUTO_DELETE DEPENDENCIES="ActionRecord" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface ActionRecord
{
    /**
     * Name of the action and group.
     * Example = FirstProductDiscount.default
     */
    name:string;
    /**
     * Address of the node storing workers
     */
    nodeAddress:string;
    /**
     * Address of the event that triggers the action.
     * A triggers address is usually the same as its name.
     */
    trigger:string;
}
