/* <ALLOW_AUTO_DELETE DEPENDENCIES="AddedToCartEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { Product } from './Product';
import { Profile } from './Profile';

export interface AddedToCartEvent
{
    profile:Profile;
    product:Product;
}
