/* <ALLOW_AUTO_DELETE DEPENDENCIES="AddedToCartEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { ProductScheme } from './ProductScheme';
import { ProfileScheme } from './ProfileScheme';

const __base__AddedToCartEventScheme=z.object({
});
const __lazy__AddedToCartEventScheme=z.object({
    profile:z.lazy(()=>ProfileScheme),
    product:z.lazy(()=>ProductScheme),
});
export const AddedToCartEventScheme:(typeof __base__AddedToCartEventScheme)=__base__AddedToCartEventScheme.merge(__lazy__AddedToCartEventScheme) as any;
