/* <ALLOW_AUTO_DELETE DEPENDENCIES="AddressedEventRecord" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface AddressedEventRecord
{
    /**
     * The address event, typically the events type or
     * name. The events address is used to match it to
     * listening actions
     */
    address:string;
    /**
     * The actual event
     */
    event:any;
}
