/* <ALLOW_AUTO_DELETE DEPENDENCIES="AddressedEventRecord" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__AddressedEventRecordScheme=z.object({
    address:z.string().max(255).describe("The address event, typically the events type or name. The events address is used to match it to listening actions"),
    event:z.any().describe("The actual event"),
});
const __lazy__AddressedEventRecordScheme=z.object({
});
export const AddressedEventRecordScheme:(typeof __base__AddressedEventRecordScheme)=__base__AddressedEventRecordScheme.merge(__lazy__AddressedEventRecordScheme) as any;
