/* <ALLOW_AUTO_DELETE DEPENDENCIES="ApiKey" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ApiKeyScheme=z.object({
    id:z.number().int(),
    name:z.string().max(255).optional(),
    created:z.number().optional(),
    expires:z.number(),
    accountId:z.number().int().optional(),
    key:z.string(),
    roles:z.string().max(255).array(),
});
const __lazy__ApiKeyScheme=z.object({
});
export const ApiKeyScheme:(typeof __base__ApiKeyScheme)=__base__ApiKeyScheme.merge(__lazy__ApiKeyScheme) as any;
