/* <ALLOW_AUTO_DELETE DEPENDENCIES="ApiKey" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ApiKey
{
    id:number;
    name?:string;
    created?:number;
    expires:number;
    accountId?:number;
    key:string;
    roles:string[];
}
