/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTriggerType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const AutomationTriggerTypeScheme=z.enum([
    "abandoned-cart",
    "event",
    "date-time",
]);
