/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationManualTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface AutomationManualTrigger
{
    automationId:number;
    nodeId:string;
    vars?:any;
    payload?:any;
    /**
     * Optional id of traverser to
     * load and resume
     */
    traverserId?:string;
    traverser?:any;
}
