/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTriggerType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "abandoned-cart",
    "event",
    "date-time"
] as const;
Object.freeze(unionAry);

export type AutomationTriggerType=typeof unionAry[number];

export const allAutomationTriggerTypeAry:AutomationTriggerType[]=unionAry as any;
