/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AutomationTriggerType } from './AutomationTriggerType';

export interface AutomationTrigger
{
    eventType?:string;
    nodeId?:string;
    data?:Record<string,any>;
    type:AutomationTriggerType;
}
