/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTraverser" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__AutomationTraverserScheme=z.object({
    id:z.number().int(),
    traverserId:z.string().max(255).optional().describe("Only not null while the traverser is active"),
    tid:z.string().max(255).describe("Copy of traverserId that is persistent"),
    automationId:z.number().int(),
    version:z.number(),
    exeState:z.string().max(255),
    runCount:z.number().int(),
    running:z.boolean(),
    created:z.number(),
    lastUpdate:z.number().optional(),
    currentNodeId:z.string().max(255).optional(),
    currentStepIndex:z.number().int(),
    startingNodeId:z.string().max(255).optional(),
    errorMessage:z.string().optional(),
    chain:z.record(z.any()),
    traverser:z.record(z.any()),
});
const __lazy__AutomationTraverserScheme=z.object({
});
export const AutomationTraverserScheme:(typeof __base__AutomationTraverserScheme)=__base__AutomationTraverserScheme.merge(__lazy__AutomationTraverserScheme) as any;
