/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTriggerRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AutomationTriggerTypeScheme } from './AutomationTriggerTypeScheme';

const __base__AutomationTriggerRecordScheme=z.object({
    id:z.number().int(),
    automationId:z.number().int(),
    eventType:z.string().max(255).optional(),
    nodeId:z.string().max(255).optional(),
    data:z.record(z.any()).optional(),
});
const __lazy__AutomationTriggerRecordScheme=z.object({
    type:z.lazy(()=>AutomationTriggerTypeScheme),
});
export const AutomationTriggerRecordScheme:(typeof __base__AutomationTriggerRecordScheme)=__base__AutomationTriggerRecordScheme.merge(__lazy__AutomationTriggerRecordScheme) as any;
