/* <ALLOW_AUTO_DELETE DEPENDENCIES="Automation" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MessageRecordScheme } from './MessageRecordScheme';
import { EventRecordScheme } from './EventRecordScheme';
import { AutomationTraverserScheme } from './AutomationTraverserScheme';
import { AutomationTriggerRecordScheme } from './AutomationTriggerRecordScheme';

const __base__AutomationScheme=z.object({
    id:z.number().int(),
    uuid:z.string().max(255),
    name:z.string().max(255),
    description:z.string().optional(),
    created:z.number(),
    lastUpdated:z.number().optional(),
    published:z.boolean().optional(),
    isDraft:z.boolean(),
    publishId:z.number().int().optional().describe("Id of an automation that this automation is a draft version of"),
    draftId:z.number().int().optional().describe("Id of an automation that this automation is a published version of"),
    iconUrl:z.string().optional(),
    tags:z.string().max(255).array().optional(),
    graph:z.record(z.any()),
});
const __lazy__AutomationScheme=z.object({
    triggers:z.lazy(()=>AutomationTriggerRecordScheme).array().optional(),
    traversers:z.lazy(()=>AutomationTraverserScheme).array().optional(),
    events:z.lazy(()=>EventRecordScheme).array().optional(),
    messages:z.lazy(()=>MessageRecordScheme).array().optional(),
});
export const AutomationScheme:(typeof __base__AutomationScheme)=__base__AutomationScheme.merge(__lazy__AutomationScheme) as any;
