/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AutomationTriggerTypeScheme } from './AutomationTriggerTypeScheme';

const __base__AutomationTriggerScheme=z.object({
    eventType:z.string().max(255).optional(),
    nodeId:z.string().max(255).optional(),
    data:z.record(z.any()).optional(),
});
const __lazy__AutomationTriggerScheme=z.object({
    type:z.lazy(()=>AutomationTriggerTypeScheme),
});
export const AutomationTriggerScheme:(typeof __base__AutomationTriggerScheme)=__base__AutomationTriggerScheme.merge(__lazy__AutomationTriggerScheme) as any;
