/* <ALLOW_AUTO_DELETE DEPENDENCIES="Automation" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageRecord } from './MessageRecord';
import type { EventRecord } from './EventRecord';
import type { AutomationTraverser } from './AutomationTraverser';
import type { AutomationTriggerRecord } from './AutomationTriggerRecord';

export interface Automation
{
    id:number;
    uuid:string;
    name:string;
    description?:string;
    created:number;
    lastUpdated?:number;
    published?:boolean;
    isDraft:boolean;
    /**
     * Id of an automation that this
     * automation is a draft version of
     */
    publishId?:number;
    /**
     * Id of an automation that this
     * automation is a published version of
     */
    draftId?:number;
    iconUrl?:string;
    tags?:string[];
    graph:Record<string,any>;
    triggers?:AutomationTriggerRecord[];
    traversers?:AutomationTraverser[];
    events?:EventRecord[];
    messages?:MessageRecord[];
}
