/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationManualTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__AutomationManualTriggerScheme=z.object({
    automationId:z.number(),
    nodeId:z.string().max(255),
    vars:z.any().optional(),
    payload:z.any().optional(),
    traverserId:z.string().max(255).optional().describe("Optional id of traverser to load and resume"),
    traverser:z.any().optional(),
});
const __lazy__AutomationManualTriggerScheme=z.object({
});
export const AutomationManualTriggerScheme:(typeof __base__AutomationManualTriggerScheme)=__base__AutomationManualTriggerScheme.merge(__lazy__AutomationManualTriggerScheme) as any;
