/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTraverser" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface AutomationTraverser
{
    id:number;
    /**
     * Only not null while the traverser is active
     */
    traverserId?:string;
    /**
     * Copy of traverserId that is persistent
     */
    tid:string;
    automationId:number;
    version:number;
    exeState:string;
    runCount:number;
    running:boolean;
    created:number;
    lastUpdate?:number;
    currentNodeId?:string;
    currentStepIndex:number;
    startingNodeId?:string;
    errorMessage?:string;
    chain:Record<string,any>;
    traverser:Record<string,any>;
}
