/* <ALLOW_AUTO_DELETE DEPENDENCIES="AutomationTriggerRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AutomationTriggerType } from './AutomationTriggerType';

export interface AutomationTriggerRecord
{
    id:number;
    automationId:number;
    eventType?:string;
    nodeId?:string;
    data?:Record<string,any>;
    type:AutomationTriggerType;
}
