/* <ALLOW_AUTO_DELETE DEPENDENCIES="ClickUpSupportFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ClickUpSupportIO } from './ClickUpSupportIO';

export interface invokeClickUpSupportFnFunctionArgs
{
    input:ClickUpSupportIO;
}
