/* <ALLOW_AUTO_DELETE DEPENDENCIES="ClickUpSupportIO" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ClickUpSupportIOScheme=z.object({
    name:z.string().max(255),
    email:z.string().email(),
    message:z.string().max(255),
    shortMessage:z.string().max(255),
    supportTypeValue:z.string().max(255),
});
const __lazy__ClickUpSupportIOScheme=z.object({
});
export const ClickUpSupportIOScheme:(typeof __base__ClickUpSupportIOScheme)=__base__ClickUpSupportIOScheme.merge(__lazy__ClickUpSupportIOScheme) as any;
