/* <ALLOW_AUTO_DELETE DEPENDENCIES="ClickUpSupportIO" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ClickUpSupportIO
{
    name:string;
    email:string;
    message:string;
    shortMessage:string;
    supportTypeValue:string;
}
