/* <ALLOW_AUTO_DELETE DEPENDENCIES="ClickUpSupportFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ClickUpSupportIOScheme } from './ClickUpSupportIOScheme';

const __base__invokeClickUpSupportFnFunctionArgsScheme=z.object({
});
const __lazy__invokeClickUpSupportFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ClickUpSupportIOScheme),
});
export const invokeClickUpSupportFnFunctionArgsScheme:(typeof __base__invokeClickUpSupportFnFunctionArgsScheme)=__base__invokeClickUpSupportFnFunctionArgsScheme.merge(__lazy__invokeClickUpSupportFnFunctionArgsScheme) as any;
