/* <ALLOW_AUTO_DELETE DEPENDENCIES="CognitoPasswordSetFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CognitoPasswordSetFnInputScheme } from './CognitoPasswordSetFnInputScheme';

const __base__invokeCognitoPasswordSetFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCognitoPasswordSetFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CognitoPasswordSetFnInputScheme),
});
export const invokeCognitoPasswordSetFnFunctionArgsScheme:(typeof __base__invokeCognitoPasswordSetFnFunctionArgsScheme)=__base__invokeCognitoPasswordSetFnFunctionArgsScheme.merge(__lazy__invokeCognitoPasswordSetFnFunctionArgsScheme) as any;
