/* <ALLOW_AUTO_DELETE DEPENDENCIES="CognitoPasswordSetFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CognitoPasswordSetFnInput } from './CognitoPasswordSetFnInput';

export interface invokeCognitoPasswordSetFnFunctionArgs
{
    input:CognitoPasswordSetFnInput;
}
