/* <ALLOW_AUTO_DELETE DEPENDENCIES="CognitoPasswordSetFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface CognitoPasswordSetFnInput
{
    email:string;
    tempPassword:string;
    password:string;
}
