/* <ALLOW_AUTO_DELETE DEPENDENCIES="CognitoPasswordSetFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__CognitoPasswordSetFnInputScheme=z.object({
    email:z.string().email(),
    tempPassword:z.string().max(255),
    password:z.string().max(255),
});
const __lazy__CognitoPasswordSetFnInputScheme=z.object({
});
export const CognitoPasswordSetFnInputScheme:(typeof __base__CognitoPasswordSetFnInputScheme)=__base__CognitoPasswordSetFnInputScheme.merge(__lazy__CognitoPasswordSetFnInputScheme) as any;
