/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommonUserRoles" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export const CommonUserRolesAry=[
    "admin",
];
