/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommonEventTypes" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
export const CommonEventTypesToAlias={
    "click": {
        "default": "c",
        "all": [
            "c"
        ]
    },
    "pageView": {
        "default": "v",
        "all": [
            "v"
        ]
    },
    "pageHidden": {
        "default": "ph",
        "all": [
            "ph"
        ]
    },
    "pageVisible": {
        "default": "pv",
        "all": [
            "pv"
        ]
    },
    "elemView": {
        "default": "ev",
        "all": [
            "ev"
        ]
    },
    "mouseover": {
        "default": "o",
        "all": [
            "o"
        ]
    },
    "mouseout": {
        "default": "j",
        "all": [
            "j"
        ]
    },
    "mousedown": {
        "default": "d",
        "all": [
            "d"
        ]
    },
    "mouseup": {
        "default": "u",
        "all": [
            "u"
        ]
    },
    "touchstart": {
        "default": "ts",
        "all": [
            "ts"
        ]
    },
    "touchend": {
        "default": "td",
        "all": [
            "td"
        ]
    },
    "touchmove": {
        "default": "tm",
        "all": [
            "tm"
        ]
    },
    "console": {
        "default": "l",
        "all": [
            "l"
        ]
    },
    "messageSent": {
        "default": "ms",
        "all": [
            "ms"
        ]
    },
    "messageOpen": {
        "default": "mo",
        "all": [
            "mo"
        ]
    },
    "messageCta": {
        "default": "mc",
        "all": [
            "mc"
        ]
    },
    "newProfile": {
        "default": "np",
        "all": [
            "np"
        ]
    },
    "cartCheckout": {
        "default": "cc",
        "all": [
            "cc"
        ]
    },
    "cartAdd": {
        "default": "ca",
        "all": [
            "ca"
        ]
    },
    "cartRemove": {
        "default": "cr",
        "all": [
            "cr"
        ]
    },
    "cartAbandon": {
        "default": "cb",
        "all": [
            "cb"
        ]
    },
    "sessionStart": {
        "default": "ss",
        "all": [
            "ss"
        ]
    }
}
export const CommonEventTypesFromAlias={
    "c": {
        "default": "click",
        "all": [
            "click"
        ]
    },
    "v": {
        "default": "pageView",
        "all": [
            "pageView"
        ]
    },
    "ph": {
        "default": "pageHidden",
        "all": [
            "pageHidden"
        ]
    },
    "pv": {
        "default": "pageVisible",
        "all": [
            "pageVisible"
        ]
    },
    "ev": {
        "default": "elemView",
        "all": [
            "elemView"
        ]
    },
    "o": {
        "default": "mouseover",
        "all": [
            "mouseover"
        ]
    },
    "j": {
        "default": "mouseout",
        "all": [
            "mouseout"
        ]
    },
    "d": {
        "default": "mousedown",
        "all": [
            "mousedown"
        ]
    },
    "u": {
        "default": "mouseup",
        "all": [
            "mouseup"
        ]
    },
    "ts": {
        "default": "touchstart",
        "all": [
            "touchstart"
        ]
    },
    "td": {
        "default": "touchend",
        "all": [
            "touchend"
        ]
    },
    "tm": {
        "default": "touchmove",
        "all": [
            "touchmove"
        ]
    },
    "l": {
        "default": "console",
        "all": [
            "console"
        ]
    },
    "ms": {
        "default": "messageSent",
        "all": [
            "messageSent"
        ]
    },
    "mo": {
        "default": "messageOpen",
        "all": [
            "messageOpen"
        ]
    },
    "mc": {
        "default": "messageCta",
        "all": [
            "messageCta"
        ]
    },
    "np": {
        "default": "newProfile",
        "all": [
            "newProfile"
        ]
    },
    "cc": {
        "default": "cartCheckout",
        "all": [
            "cartCheckout"
        ]
    },
    "ca": {
        "default": "cartAdd",
        "all": [
            "cartAdd"
        ]
    },
    "cr": {
        "default": "cartRemove",
        "all": [
            "cartRemove"
        ]
    },
    "cb": {
        "default": "cartAbandon",
        "all": [
            "cartAbandon"
        ]
    },
    "ss": {
        "default": "sessionStart",
        "all": [
            "sessionStart"
        ]
    }
}
