/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommonEventTypes" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
export const CommonEventTypesToAlias={
    "click": {
        "default": "c",
        "all": [
            "c"
        ]
    },
    "pageView": {
        "default": "v",
        "all": [
            "v"
        ]
    },
    "pageHidden": {
        "default": "ph",
        "all": [
            "ph"
        ]
    },
    "pageVisible": {
        "default": "pv",
        "all": [
            "pv"
        ]
    },
    "elemView": {
        "default": "ev",
        "all": [
            "ev"
        ]
    },
    "mouseover": {
        "default": "o",
        "all": [
            "o"
        ]
    },
    "mouseout": {
        "default": "j",
        "all": [
            "j"
        ]
    },
    "mousedown": {
        "default": "d",
        "all": [
            "d"
        ]
    },
    "mouseup": {
        "default": "u",
        "all": [
            "u"
        ]
    },
    "touchstart": {
        "default": "ts",
        "all": [
            "ts"
        ]
    },
    "touchend": {
        "default": "td",
        "all": [
            "td"
        ]
    },
    "touchmove": {
        "default": "tm",
        "all": [
            "tm"
        ]
    },
    "console": {
        "default": "l",
        "all": [
            "l"
        ]
    }
}
export const CommonEventTypesFromAlias={
    "c": {
        "default": "click",
        "all": [
            "click"
        ]
    },
    "v": {
        "default": "pageView",
        "all": [
            "pageView"
        ]
    },
    "ph": {
        "default": "pageHidden",
        "all": [
            "pageHidden"
        ]
    },
    "pv": {
        "default": "pageVisible",
        "all": [
            "pageVisible"
        ]
    },
    "ev": {
        "default": "elemView",
        "all": [
            "elemView"
        ]
    },
    "o": {
        "default": "mouseover",
        "all": [
            "mouseover"
        ]
    },
    "j": {
        "default": "mouseout",
        "all": [
            "mouseout"
        ]
    },
    "d": {
        "default": "mousedown",
        "all": [
            "mousedown"
        ]
    },
    "u": {
        "default": "mouseup",
        "all": [
            "mouseup"
        ]
    },
    "ts": {
        "default": "touchstart",
        "all": [
            "touchstart"
        ]
    },
    "td": {
        "default": "touchend",
        "all": [
            "touchend"
        ]
    },
    "tm": {
        "default": "touchmove",
        "all": [
            "touchmove"
        ]
    },
    "l": {
        "default": "console",
        "all": [
            "console"
        ]
    }
}
