/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommsChannel" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "email",
    "sms",
    "notification"
] as const;
Object.freeze(unionAry);

export type CommsChannel=typeof unionAry[number];

export const allCommsChannelAry:CommsChannel[]=unionAry as any;
