/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommonEventTypes" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export const CommonEventTypesAry=[
    "click",
    "pageView",
    "pageHidden",
    "pageVisible",
    "elemView",
    "mouseover",
    "mouseout",
    "mousedown",
    "mouseup",
    "touchstart",
    "touchend",
    "touchmove",
    "console",
];

export const CommonEventTypesMap={
    "click":"click",
    "pageView":"pageView",
    "pageHidden":"pageHidden",
    "pageVisible":"pageVisible",
    "elemView":"elemView",
    "mouseover":"mouseover",
    "mouseout":"mouseout",
    "mousedown":"mousedown",
    "mouseup":"mouseup",
    "touchstart":"touchstart",
    "touchend":"touchend",
    "touchmove":"touchmove",
    "console":"console",
};
