/* <ALLOW_AUTO_DELETE DEPENDENCIES="CommonTemplateItemActions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export const CommonTemplateItemActionsMap={
    "next":"next",
    "subscribe":"subscribe",
};
