/* <ALLOW_AUTO_DELETE DEPENDENCIES="ContactRequestEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__ContactRequestEventScheme=z.object({
    email:z.string().email(),
    message:z.string().max(255),
});
const __lazy__ContactRequestEventScheme=z.object({
});
export const ContactRequestEventScheme:(typeof __base__ContactRequestEventScheme)=__base__ContactRequestEventScheme.merge(__lazy__ContactRequestEventScheme) as any;
