/* <ALLOW_AUTO_DELETE DEPENDENCIES="ContactRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface ContactRequest
{
    id:string;
    uv:number;
    created:number;
    name?:string;
    email?:string;
    phone?:string;
    tag:string;
}
