/* <ALLOW_AUTO_DELETE DEPENDENCIES="ContactRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ContactRequest
{
    id:string;
    uv:number;
    created:number;
    name?:string;
    email?:string;
    phone?:string;
    tag:string;
}
