/* <ALLOW_AUTO_DELETE DEPENDENCIES="ContactRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__ContactRequestScheme=z.object({
    id:z.string().max(255),
    uv:z.number().int(),
    created:z.number(),
    name:z.string().max(255).optional(),
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
    tag:z.string().max(255),
});
const __lazy__ContactRequestScheme=z.object({
});
export const ContactRequestScheme:(typeof __base__ContactRequestScheme)=__base__ContactRequestScheme.merge(__lazy__ContactRequestScheme) as any;
