/* <ALLOW_AUTO_DELETE DEPENDENCIES="ContactRequestEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface ContactRequestEvent
{
    email:string;
    message:string;
}
