/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateFileRecordRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface CreateFileRecordRequest
{
    /**
     * If true external URLs should be downloaded and
     * moved to the media bucket
     */
    importExternal?:boolean;
    /**
     * If true CreateFileRecordFn will download and
     * update the URLs of the request in the background
     * after CreateFileRecords returns. The returned
     * FileRecord will have still have the external
     * URLs of the request.
     */
    importInBackground?:boolean;
    id?:number;
    userId?:number;
    accountId?:number;
    created?:number;
    lastModified?:number;
    name:string;
    description?:string;
    altId?:string;
    smUrl?:string;
    smContentType?:string;
    smWidth?:number;
    smHeight?:number;
    smSizeBytes?:number;
    smExternal?:boolean;
    mdUrl?:string;
    mdContentType?:string;
    mdWidth?:number;
    mdHeight?:number;
    mdSizeBytes?:number;
    mdExternal?:boolean;
    lgUrl?:string;
    lgContentType?:string;
    lgWidth?:number;
    lgHeight?:number;
    lgSizeBytes?:number;
    lgExternal?:boolean;
    srcUrl:string;
    srcContentType?:string;
    srcWidth?:number;
    srcHeight?:number;
    srcSizeBytes?:number;
    srcExternal?:boolean;
    blurhash?:string;
    /**
     * Where the file was sourced from.
     * For example files sourced from
     * Unsplash should use a source
     * of "unsplash"
     */
    source?:string;
    /**
     * An approximation of the overall
     * color of the file
     */
    color?:string;
}
