/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateDomainFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CreateDomainRequest } from './CreateDomainRequest';

export interface invokeCreateDomainFnFunctionArgs
{
    input:CreateDomainRequest;
}
