/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAccountRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountLlmPropertiesScheme } from './AccountLlmPropertiesScheme';
import { AccountThemeScheme } from './AccountThemeScheme';
import { EmailAttributionEventTypeScheme } from './EmailAttributionEventTypeScheme';
import { AccountTypeScheme } from './AccountTypeScheme';
import { CurrencyScheme } from './CurrencyScheme';

const __base__CreateAccountRequestScheme=z.object({
    name:z.string().max(255),
    timezone:z.string().max(255),
    joinUser:z.boolean().optional().describe("If true the calling user will be joined to the account as an admin. If the user is already a member of another account the user will leave that account."),
    description:z.string().optional(),
    industry:z.string().max(255).optional(),
    mfaRequired:z.boolean().optional(),
    minProfileSendIntervalMs:z.number().int().optional(),
    messageSubjectPreviewPrefix:z.string().max(255).optional(),
    placeEmailTrackingPixelAtBottom:z.boolean().optional(),
    websiteUrl:z.string().optional(),
    logoUrl:z.string().optional(),
    country:z.string().max(255).optional(),
    state:z.string().max(255).optional(),
    city:z.string().max(255).optional(),
    address:z.string().max(255).optional(),
    address2:z.string().max(255).optional(),
    postalCode:z.string().max(255).optional(),
    defaultSenderName:z.string().max(255).optional(),
    defaultSenderEmail:z.string().email().optional(),
    platformUsages:z.string().max(255).array().optional(),
    privacyPolicyUrl:z.string().optional(),
    termsUrl:z.string().optional(),
    minMessageSendIntervalHours:z.number().optional(),
    messagePreviewPrefix:z.string().optional(),
    autoUpgrade:z.boolean().optional(),
    emailAttributionTime:z.number().int().optional(),
    smsAttributionTime:z.number().int().optional(),
    notificationAttributionTime:z.number().int().optional(),
    notificationCompanyName:z.string().max(255).optional(),
    notificationMinMessageSendIntervalHours:z.number().optional(),
    notificationLogoUrl:z.string().optional(),
});
const __lazy__CreateAccountRequestScheme=z.object({
    currency:z.lazy(()=>CurrencyScheme),
    type:z.lazy(()=>AccountTypeScheme).optional(),
    emailAttributionType:z.lazy(()=>EmailAttributionEventTypeScheme).optional(),
    theme:z.lazy(()=>AccountThemeScheme).optional(),
    llmProperties:z.lazy(()=>AccountLlmPropertiesScheme).optional(),
});
export const CreateAccountRequestScheme:(typeof __base__CreateAccountRequestScheme)=__base__CreateAccountRequestScheme.merge(__lazy__CreateAccountRequestScheme) as any;
