/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateUserFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { User } from './User';

export interface invokeCreateUserFnFunctionArgs
{
    input:User;
}
