/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateProfileGroupOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryScheme } from './QueryScheme';
import { ProfileGroupTypeScheme } from './ProfileGroupTypeScheme';

const __base__CreateProfileGroupOptionsScheme=z.object({
    name:z.string().max(255),
});
const __lazy__CreateProfileGroupOptionsScheme=z.object({
    type:z.lazy(()=>ProfileGroupTypeScheme),
    query:z.lazy(()=>QueryScheme).optional(),
});
export const CreateProfileGroupOptionsScheme:(typeof __base__CreateProfileGroupOptionsScheme)=__base__CreateProfileGroupOptionsScheme.merge(__lazy__CreateProfileGroupOptionsScheme) as any;
