/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateCustomUserMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Creates a custom email/SMS when
 * Cognito sends a message
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeCreateCustomUserMessageFnFunctionArgs
{
}
