/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateMessageRecordOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MessageTemplateScheme } from './MessageTemplateScheme';
import { EventRecordScheme } from './EventRecordScheme';
import { CommsChannelScheme } from './CommsChannelScheme';

const __base__CreateMessageRecordOptionsScheme=z.object({
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
    deviceId:z.number().int().optional(),
    profileId:z.number().int().optional(),
    userId:z.number().int().optional(),
    accountId:z.number().int().optional(),
    senderId:z.number().int().optional(),
    created:z.number().optional(),
    sentAt:z.number().optional(),
    deliveredAt:z.number().optional(),
    openedAt:z.number().optional(),
    sendErrorMessage:z.string().optional(),
    sendFailedAt:z.number().optional(),
    templateId:z.number().int().optional(),
    data:z.record(z.any()).optional(),
    sendAttempts:z.number().int().optional(),
    automationId:z.number().int().optional(),
    automationNodeId:z.string().max(255).optional(),
    sesMessageId:z.string().max(255).optional(),
}).describe("Represents a sent message");
const __lazy__CreateMessageRecordOptionsScheme=z.object({
    preferredChannel:z.lazy(()=>CommsChannelScheme).optional(),
    events:z.lazy(()=>EventRecordScheme).array().optional(),
    inlineTemplate:z.lazy(()=>MessageTemplateScheme).optional().describe("An inline template used for only this messages"),
    channel:z.lazy(()=>CommsChannelScheme).optional(),
});
export const CreateMessageRecordOptionsScheme:(typeof __base__CreateMessageRecordOptionsScheme)=__base__CreateMessageRecordOptionsScheme.merge(__lazy__CreateMessageRecordOptionsScheme) as any;
