/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateApiKeyRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__CreateApiKeyRequestScheme=z.object({
    name:z.string().max(255),
    expires:z.number(),
    roles:z.string().max(255).array().optional(),
});
const __lazy__CreateApiKeyRequestScheme=z.object({
});
export const CreateApiKeyRequestScheme:(typeof __base__CreateApiKeyRequestScheme)=__base__CreateApiKeyRequestScheme.merge(__lazy__CreateApiKeyRequestScheme) as any;
