/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateProfileGroupOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query } from './Query';
import type { ProfileGroupType } from './ProfileGroupType';

export interface CreateProfileGroupOptions
{
    name:string;
    type:ProfileGroupType;
    query?:Query;
}
