/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateApiKeyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CreateApiKeyRequestScheme } from './CreateApiKeyRequestScheme';

const __base__invokeCreateApiKeyFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateApiKeyFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CreateApiKeyRequestScheme),
});
export const invokeCreateApiKeyFnFunctionArgsScheme:(typeof __base__invokeCreateApiKeyFnFunctionArgsScheme)=__base__invokeCreateApiKeyFnFunctionArgsScheme.merge(__lazy__invokeCreateApiKeyFnFunctionArgsScheme) as any;
