/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AutomationScheme } from './AutomationScheme';

const __base__invokeCreateAutomationFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateAutomationFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>AutomationScheme),
});
export const invokeCreateAutomationFnFunctionArgsScheme:(typeof __base__invokeCreateAutomationFnFunctionArgsScheme)=__base__invokeCreateAutomationFnFunctionArgsScheme.merge(__lazy__invokeCreateAutomationFnFunctionArgsScheme) as any;
