/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateWorkerRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { UserScheme } from './UserScheme';

const __base__CreateWorkerRequestScheme=z.object({
    address:z.string().max(255),
});
const __lazy__CreateWorkerRequestScheme=z.object({
    user:z.lazy(()=>UserScheme),
});
export const CreateWorkerRequestScheme:(typeof __base__CreateWorkerRequestScheme)=__base__CreateWorkerRequestScheme.merge(__lazy__CreateWorkerRequestScheme) as any;
