/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateApiKeyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CreateApiKeyRequest } from './CreateApiKeyRequest';

export interface invokeCreateApiKeyFnFunctionArgs
{
    input:CreateApiKeyRequest;
}
