/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateCustomFieldFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CustomFieldScheme } from './CustomFieldScheme';

const __base__invokeCreateCustomFieldFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateCustomFieldFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CustomFieldScheme),
});
export const invokeCreateCustomFieldFnFunctionArgsScheme:(typeof __base__invokeCreateCustomFieldFnFunctionArgsScheme)=__base__invokeCreateCustomFieldFnFunctionArgsScheme.merge(__lazy__invokeCreateCustomFieldFnFunctionArgsScheme) as any;
