/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateQueryRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { QueryRecord } from './QueryRecord';

/**
 * Creates a new query record
 */
export interface invokeCreateQueryRecordFunctionArgs
{
    input:QueryRecord;
}
