/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateUserFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { UserScheme } from './UserScheme';

const __base__invokeCreateUserFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateUserFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>UserScheme),
});
export const invokeCreateUserFnFunctionArgsScheme:(typeof __base__invokeCreateUserFnFunctionArgsScheme)=__base__invokeCreateUserFnFunctionArgsScheme.merge(__lazy__invokeCreateUserFnFunctionArgsScheme) as any;
