/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateWorkerFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { CreateWorkerRequestScheme } from './CreateWorkerRequestScheme';

const __base__invokeCreateWorkerFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateWorkerFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CreateWorkerRequestScheme),
});
export const invokeCreateWorkerFnFunctionArgsScheme:(typeof __base__invokeCreateWorkerFnFunctionArgsScheme)=__base__invokeCreateWorkerFnFunctionArgsScheme.merge(__lazy__invokeCreateWorkerFnFunctionArgsScheme) as any;
