/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateMessageRecordOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageTemplate } from './MessageTemplate';
import type { EventRecord } from './EventRecord';
import type { CommsChannel } from './CommsChannel';

/**
 * Represents a sent message
 */
export interface CreateMessageRecordOptions
{
    email?:string;
    phone?:string;
    deviceId?:number;
    profileId?:number;
    userId?:number;
    accountId?:number;
    senderId?:number;
    created?:number;
    sentAt?:number;
    deliveredAt?:number;
    openedAt?:number;
    sendErrorMessage?:string;
    sendFailedAt?:number;
    templateId?:number;
    data?:Record<string,any>;
    sendAttempts?:number;
    automationId?:number;
    automationNodeId?:string;
    sesMessageId?:string;
    preferredChannel?:CommsChannel;
    events?:EventRecord[];
    /**
     * An inline template used for only this messages
     */
    inlineTemplate?:MessageTemplate;
    channel?:CommsChannel;
}
