/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CreateProfileGroupOptions } from './CreateProfileGroupOptions';

export interface invokeCreateProfileGroupFnFunctionArgs
{
    input:CreateProfileGroupOptions;
}
