/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateQueryRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryRecordScheme } from './QueryRecordScheme';

const __base__invokeCreateQueryRecordFunctionArgsScheme=z.object({
}).describe("Creates a new query record");
const __lazy__invokeCreateQueryRecordFunctionArgsScheme=z.object({
    input:z.lazy(()=>QueryRecordScheme),
});
export const invokeCreateQueryRecordFunctionArgsScheme:(typeof __base__invokeCreateQueryRecordFunctionArgsScheme)=__base__invokeCreateQueryRecordFunctionArgsScheme.merge(__lazy__invokeCreateQueryRecordFunctionArgsScheme) as any;
