/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateWorkerFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { CreateWorkerRequest } from './CreateWorkerRequest';

export interface invokeCreateWorkerFnFunctionArgs
{
    input:CreateWorkerRequest;
}
