/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAccountRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountLlmProperties } from './AccountLlmProperties';
import type { AccountTheme } from './AccountTheme';
import type { EmailAttributionEventType } from './EmailAttributionEventType';
import type { AccountType } from './AccountType';
import type { Currency } from './Currency';

export interface CreateAccountRequest
{
    name:string;
    timezone:string;
    /**
     * If true the calling user will be joined to the account
     * as an admin. If the user is already a member of another
     * account the user will leave that account.
     */
    joinUser?:boolean;
    description?:string;
    industry?:string;
    mfaRequired?:boolean;
    minProfileSendIntervalMs?:number;
    messageSubjectPreviewPrefix?:string;
    placeEmailTrackingPixelAtBottom?:boolean;
    websiteUrl?:string;
    logoUrl?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    defaultSenderName?:string;
    defaultSenderEmail?:string;
    platformUsages?:string[];
    privacyPolicyUrl?:string;
    termsUrl?:string;
    minMessageSendIntervalHours?:number;
    messagePreviewPrefix?:string;
    autoUpgrade?:boolean;
    emailAttributionTime?:number;
    smsAttributionTime?:number;
    notificationAttributionTime?:number;
    notificationCompanyName?:string;
    notificationMinMessageSendIntervalHours?:number;
    notificationLogoUrl?:string;
    currency:Currency;
    type?:AccountType;
    emailAttributionType?:EmailAttributionEventType;
    theme?:AccountTheme;
    llmProperties?:AccountLlmProperties;
}
