/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateCustomUserMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeCreateCustomUserMessageFnFunctionArgsScheme=z.object({
}).describe("Creates a custom email/SMS when Cognito sends a message");
const __lazy__invokeCreateCustomUserMessageFnFunctionArgsScheme=z.object({
});
export const invokeCreateCustomUserMessageFnFunctionArgsScheme:(typeof __base__invokeCreateCustomUserMessageFnFunctionArgsScheme)=__base__invokeCreateCustomUserMessageFnFunctionArgsScheme.merge(__lazy__invokeCreateCustomUserMessageFnFunctionArgsScheme) as any;
