/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateDomainRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface CreateDomainRequest
{
    /**
     * The root (apex) name of the domain
     */
    name:string;
    /**
     * Enables analytics and allows events
     * from the domain to be received and
     * processed by the account.
     */
    eventsCollectionEnabled?:boolean;
    emailSendingEnabled?:boolean;
    emailSendingSubdomain?:string;
    emailSendingVerified?:boolean;
}
