/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateApiKeyRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface CreateApiKeyRequest
{
    name:string;
    expires:number;
    roles?:string[];
}
