/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateFileRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CreateFileRecordRequest } from './CreateFileRecordRequest';

export interface invokeCreateFileRecordFnFunctionArgs
{
    input:CreateFileRecordRequest;
}
