/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CreateProfileGroupOptionsScheme } from './CreateProfileGroupOptionsScheme';

const __base__invokeCreateProfileGroupFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateProfileGroupFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CreateProfileGroupOptionsScheme),
});
export const invokeCreateProfileGroupFnFunctionArgsScheme:(typeof __base__invokeCreateProfileGroupFnFunctionArgsScheme)=__base__invokeCreateProfileGroupFnFunctionArgsScheme.merge(__lazy__invokeCreateProfileGroupFnFunctionArgsScheme) as any;
