/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CreateAccountRequestScheme } from './CreateAccountRequestScheme';

const __base__invokeCreateAccountFnFunctionArgsScheme=z.object({
});
const __lazy__invokeCreateAccountFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CreateAccountRequestScheme),
});
export const invokeCreateAccountFnFunctionArgsScheme:(typeof __base__invokeCreateAccountFnFunctionArgsScheme)=__base__invokeCreateAccountFnFunctionArgsScheme.merge(__lazy__invokeCreateAccountFnFunctionArgsScheme) as any;
