/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateDomainRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__CreateDomainRequestScheme=z.object({
    name:z.string().max(255).describe("The root (apex) name of the domain"),
    eventsCollectionEnabled:z.boolean().optional().describe("Enables analytics and allows events from the domain to be received and processed by the account."),
    emailSendingEnabled:z.boolean().optional(),
    emailSendingSubdomain:z.string().max(255).optional(),
    emailSendingVerified:z.boolean().optional(),
});
const __lazy__CreateDomainRequestScheme=z.object({
});
export const CreateDomainRequestScheme:(typeof __base__CreateDomainRequestScheme)=__base__CreateDomainRequestScheme.merge(__lazy__CreateDomainRequestScheme) as any;
