/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CreateAccountRequest } from './CreateAccountRequest';

export interface invokeCreateAccountFnFunctionArgs
{
    input:CreateAccountRequest;
}
