/* <ALLOW_AUTO_DELETE DEPENDENCIES="CreateAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Automation } from './Automation';

export interface invokeCreateAutomationFnFunctionArgs
{
    input:Automation;
}
