/* <ALLOW_AUTO_DELETE DEPENDENCIES="Currency" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const CurrencyScheme=z.enum([
    "usd",
]);
