/* <ALLOW_AUTO_DELETE DEPENDENCIES="Currency" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "usd"
] as const;
Object.freeze(unionAry);

export type Currency=typeof unionAry[number];

export const allCurrencyAry:Currency[]=unionAry as any;
