/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomField" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CustomFieldUnionValue } from './CustomFieldUnionValue';
import type { CustomFieldType } from './CustomFieldType';

export interface CustomField
{
    id:number;
    /**
     * The name of the field as it is used in
     * code and stored in the database.
     */
    name:string;
    /**
     * A friendly display named show to the user
     */
    displayName?:string;
    /**
     * A short description of the field
     */
    description?:string;
    /**
     * A regular expression used to validate the
     * value of the field
     */
    formatReg?:string;
    /**
     * If true a user can select multiple union values
     */
    multiSelect?:boolean;
    /**
     * The max string length of the field
     */
    maxLength?:number;
    /**
     * The min string length of the field
     */
    minLength?:number;
    /**
     * If true the field is required
     */
    required?:boolean;
    /**
     * If the field has a type of "record", recordType
     * can be used determine the structure of the field
     */
    recordType?:string;
    /**
     * The datatype of the field
     */
    type:CustomFieldType;
    unionValues?:CustomFieldUnionValue[];
}
