/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldUnionValue" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CustomFieldTypeScheme } from './CustomFieldTypeScheme';

const __base__CustomFieldUnionValueScheme=z.object({
    displayName:z.string().max(255).optional(),
    value:z.any(),
});
const __lazy__CustomFieldUnionValueScheme=z.object({
    type:z.lazy(()=>CustomFieldTypeScheme),
});
export const CustomFieldUnionValueScheme:(typeof __base__CustomFieldUnionValueScheme)=__base__CustomFieldUnionValueScheme.merge(__lazy__CustomFieldUnionValueScheme) as any;
