/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const CustomFieldTypeScheme=z.enum([
    "string",
    "number",
    "boolean",
    "phone",
    "email",
    "date",
    "timestamp",
    "union",
    "any",
    "record",
]).describe("\n- record - Records are treated as JSON values\n */");
