/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldUnionValue" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CustomFieldType } from './CustomFieldType';

export interface CustomFieldUnionValue
{
    displayName?:string;
    value:any;
    type:CustomFieldType;
}
