/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldsUpdateRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface CustomFieldsUpdateRequest
{
    /**
     * GardenIQ profile id
     */
    profileId?:number;
    /**
     * External alternate profile id
     */
    altProfileId?:string;
    /**
     * An object containing custom field
     * name value pairs to add to the target
     * user profile
     */
    setFields?:Record<string,any>;
    /**
     * An array of keys to delete from the
     * target user profile's custom data
     */
    deleteFields?:string[];
}
