/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldsUpdateRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__CustomFieldsUpdateRequestScheme=z.object({
    profileId:z.number().int().optional().describe("GardenIQ profile id"),
    altProfileId:z.string().max(255).optional().describe("External alternate profile id"),
    setFields:z.record(z.any()).optional().describe("An object containing custom field name value pairs to add to the target user profile"),
    deleteFields:z.string().max(255).array().optional().describe("An array of keys to delete from the target user profile's custom data"),
});
const __lazy__CustomFieldsUpdateRequestScheme=z.object({
});
export const CustomFieldsUpdateRequestScheme:(typeof __base__CustomFieldsUpdateRequestScheme)=__base__CustomFieldsUpdateRequestScheme.merge(__lazy__CustomFieldsUpdateRequestScheme) as any;
