/* <ALLOW_AUTO_DELETE DEPENDENCIES="CustomFieldType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "string",
    "number",
    "boolean",
    "phone",
    "email",
    "date",
    "timestamp",
    "union",
    "any",
    "record"
] as const;
Object.freeze(unionAry);

/**
 * 
 * - record - Records are treated as JSON values
 */
export type CustomFieldType=typeof unionAry[number];

/**
 * 
 * - record - Records are treated as JSON values
 */
export const allCustomFieldTypeAry:CustomFieldType[]=unionAry as any;
