/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteAutomationFnFunctionArgsScheme=z.object({
    input:z.number(),
});
const __lazy__invokeDeleteAutomationFnFunctionArgsScheme=z.object({
});
export const invokeDeleteAutomationFnFunctionArgsScheme:(typeof __base__invokeDeleteAutomationFnFunctionArgsScheme)=__base__invokeDeleteAutomationFnFunctionArgsScheme.merge(__lazy__invokeDeleteAutomationFnFunctionArgsScheme) as any;
