/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteApiKeyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeDeleteApiKeyFnFunctionArgs
{
    /**
     * Id of the API key to delete
     */
    input:number;
}
