/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteMessageTemplateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeDeleteMessageTemplateFnFunctionArgs
{
    /**
     * Message Template id
     */
    input:number;
}
