/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteMessageTemplateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteMessageTemplateFnFunctionArgsScheme=z.object({
    input:z.number().describe("Message Template id"),
});
const __lazy__invokeDeleteMessageTemplateFnFunctionArgsScheme=z.object({
});
export const invokeDeleteMessageTemplateFnFunctionArgsScheme:(typeof __base__invokeDeleteMessageTemplateFnFunctionArgsScheme)=__base__invokeDeleteMessageTemplateFnFunctionArgsScheme.merge(__lazy__invokeDeleteMessageTemplateFnFunctionArgsScheme) as any;
