/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteDomainFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteDomainFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of the domain to delete"),
});
const __lazy__invokeDeleteDomainFnFunctionArgsScheme=z.object({
});
export const invokeDeleteDomainFnFunctionArgsScheme:(typeof __base__invokeDeleteDomainFnFunctionArgsScheme)=__base__invokeDeleteDomainFnFunctionArgsScheme.merge(__lazy__invokeDeleteDomainFnFunctionArgsScheme) as any;
