/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteApiKeyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteApiKeyFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of the API key to delete"),
});
const __lazy__invokeDeleteApiKeyFnFunctionArgsScheme=z.object({
});
export const invokeDeleteApiKeyFnFunctionArgsScheme:(typeof __base__invokeDeleteApiKeyFnFunctionArgsScheme)=__base__invokeDeleteApiKeyFnFunctionArgsScheme.merge(__lazy__invokeDeleteApiKeyFnFunctionArgsScheme) as any;
