/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteFormRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteFormRecordFnFunctionArgsScheme=z.object({
    input:z.number().describe("Form record id"),
});
const __lazy__invokeDeleteFormRecordFnFunctionArgsScheme=z.object({
});
export const invokeDeleteFormRecordFnFunctionArgsScheme:(typeof __base__invokeDeleteFormRecordFnFunctionArgsScheme)=__base__invokeDeleteFormRecordFnFunctionArgsScheme.merge(__lazy__invokeDeleteFormRecordFnFunctionArgsScheme) as any;
