/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteCustomFieldFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteCustomFieldFnFunctionArgsScheme=z.object({
    input:z.number(),
});
const __lazy__invokeDeleteCustomFieldFnFunctionArgsScheme=z.object({
});
export const invokeDeleteCustomFieldFnFunctionArgsScheme:(typeof __base__invokeDeleteCustomFieldFnFunctionArgsScheme)=__base__invokeDeleteCustomFieldFnFunctionArgsScheme.merge(__lazy__invokeDeleteCustomFieldFnFunctionArgsScheme) as any;
