/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteFileRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteFileRecordFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of file record to delete"),
});
const __lazy__invokeDeleteFileRecordFnFunctionArgsScheme=z.object({
});
export const invokeDeleteFileRecordFnFunctionArgsScheme:(typeof __base__invokeDeleteFileRecordFnFunctionArgsScheme)=__base__invokeDeleteFileRecordFnFunctionArgsScheme.merge(__lazy__invokeDeleteFileRecordFnFunctionArgsScheme) as any;
