/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteUserFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteUserFnFunctionArgsScheme=z.object({
    input:z.number(),
});
const __lazy__invokeDeleteUserFnFunctionArgsScheme=z.object({
});
export const invokeDeleteUserFnFunctionArgsScheme:(typeof __base__invokeDeleteUserFnFunctionArgsScheme)=__base__invokeDeleteUserFnFunctionArgsScheme.merge(__lazy__invokeDeleteUserFnFunctionArgsScheme) as any;
