/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteFileRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeDeleteFileRecordFnFunctionArgs
{
    /**
     * Id of file record to delete
     */
    input:number;
}
