/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteFormRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeDeleteFormRecordFnFunctionArgs
{
    /**
     * Form record id
     */
    input:number;
}
