/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDeleteProfileGroupFnFunctionArgsScheme=z.object({
    input:z.number(),
});
const __lazy__invokeDeleteProfileGroupFnFunctionArgsScheme=z.object({
});
export const invokeDeleteProfileGroupFnFunctionArgsScheme:(typeof __base__invokeDeleteProfileGroupFnFunctionArgsScheme)=__base__invokeDeleteProfileGroupFnFunctionArgsScheme.merge(__lazy__invokeDeleteProfileGroupFnFunctionArgsScheme) as any;
