/* <ALLOW_AUTO_DELETE DEPENDENCIES="DeleteDomainFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeDeleteDomainFnFunctionArgs
{
    /**
     * Id of the domain to delete
     */
    input:number;
}
