/* <ALLOW_AUTO_DELETE DEPENDENCIES="DiscountMessageRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { MessageChannelScheme } from './MessageChannelScheme';
import { UserScheme } from './UserScheme';
import { ProductScheme } from './ProductScheme';

const __base__DiscountMessageRequestScheme=z.object({
    id:z.string().max(255),
    template:z.string().max(255),
    discountPercent:z.number().optional(),
    discount:z.number().optional(),
});
const __lazy__DiscountMessageRequestScheme=z.object({
    product:z.lazy(()=>ProductScheme),
    user:z.lazy(()=>UserScheme),
    channel:z.lazy(()=>MessageChannelScheme).optional(),
});
export const DiscountMessageRequestScheme:(typeof __base__DiscountMessageRequestScheme)=__base__DiscountMessageRequestScheme.merge(__lazy__DiscountMessageRequestScheme) as any;
