/* <ALLOW_AUTO_DELETE DEPENDENCIES="DiscountMessageRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { MessageChannel } from './MessageChannel';
import { User } from './User';
import { Product } from './Product';

export interface DiscountMessageRequest
{
    id:string;
    template:string;
    discountPercent?:number;
    discount?:number;
    product:Product;
    user:User;
    channel?:MessageChannel;
}
