/* <ALLOW_AUTO_DELETE DEPENDENCIES="DnsRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface DnsRecord
{
    type:string;
    name:string;
    value:string;
    description?:string;
}
