/* <ALLOW_AUTO_DELETE DEPENDENCIES="DnsRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__DnsRecordScheme=z.object({
    type:z.string().max(255),
    name:z.string().max(255),
    value:z.string(),
    description:z.string().optional(),
});
const __lazy__DnsRecordScheme=z.object({
});
export const DnsRecordScheme:(typeof __base__DnsRecordScheme)=__base__DnsRecordScheme.merge(__lazy__DnsRecordScheme) as any;
