/* <ALLOW_AUTO_DELETE DEPENDENCIES="Domain" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { DnsRecordScheme } from './DnsRecordScheme';

const __base__DomainScheme=z.object({
    id:z.number().int(),
    name:z.string().max(255).describe("The root (apex) name of the domain"),
    eventsCollectionEnabled:z.boolean().optional().describe("Enables analytics and allows events from the domain to be received and processed by the account."),
    emailSendingEnabled:z.boolean().optional(),
    emailSendingSubdomain:z.string().max(255).optional(),
    emailSendingVerified:z.boolean().optional(),
});
const __lazy__DomainScheme=z.object({
    emailDnsRecords:z.lazy(()=>DnsRecordScheme).array().optional(),
});
export const DomainScheme:(typeof __base__DomainScheme)=__base__DomainScheme.merge(__lazy__DomainScheme) as any;
