/* <ALLOW_AUTO_DELETE DEPENDENCIES="Domain" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { DnsRecord } from './DnsRecord';

export interface Domain
{
    id:number;
    /**
     * The root (apex) name of the domain
     */
    name:string;
    /**
     * Enables analytics and allows events
     * from the domain to be received and
     * processed by the account.
     */
    eventsCollectionEnabled?:boolean;
    emailSendingEnabled?:boolean;
    emailSendingSubdomain?:string;
    emailSendingVerified?:boolean;
    emailDnsRecords?:DnsRecord[];
}
