/* <ALLOW_AUTO_DELETE DEPENDENCIES="DomainStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface DomainStatus
{
    /**
     * If true analytics is enabled
     */
    eventsReceived:boolean;
    emailDnsConfigured:boolean;
    emailDomainConnected:boolean;
}
