/* <ALLOW_AUTO_DELETE DEPENDENCIES="DomainStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__DomainStatusScheme=z.object({
    eventsReceived:z.boolean().describe("If true analytics is enabled"),
    emailDnsConfigured:z.boolean(),
    emailDomainConnected:z.boolean(),
});
const __lazy__DomainStatusScheme=z.object({
});
export const DomainStatusScheme:(typeof __base__DomainStatusScheme)=__base__DomainStatusScheme.merge(__lazy__DomainStatusScheme) as any;
