/* <ALLOW_AUTO_DELETE DEPENDENCIES="DuplicateProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeDuplicateProfileGroupFnFunctionArgsScheme=z.object({
    input:z.number(),
});
const __lazy__invokeDuplicateProfileGroupFnFunctionArgsScheme=z.object({
});
export const invokeDuplicateProfileGroupFnFunctionArgsScheme:(typeof __base__invokeDuplicateProfileGroupFnFunctionArgsScheme)=__base__invokeDuplicateProfileGroupFnFunctionArgsScheme.merge(__lazy__invokeDuplicateProfileGroupFnFunctionArgsScheme) as any;
