/* <ALLOW_AUTO_DELETE DEPENDENCIES="EmailAttributionEventType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const EmailAttributionEventTypeScheme=z.enum([
    "openOrClick",
    "openOrClickExclueApplePrivacy",
    "click",
]);
