/* <ALLOW_AUTO_DELETE DEPENDENCIES="EmailAttributionEventType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "openOrClick",
    "openOrClickExclueApplePrivacy",
    "click"
] as const;
Object.freeze(unionAry);

export type EmailAttributionEventType=typeof unionAry[number];

export const allEmailAttributionEventTypeAry:EmailAttributionEventType[]=unionAry as any;
