/* <ALLOW_AUTO_DELETE DEPENDENCIES="EmailAttributionEventType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type EmailAttributionEventType=(
    "openOrClick"|
    "openOrClickExclueApplePrivacy"|
    "click"
);
