/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventSubmission" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { AddressedEventRecordScheme } from './AddressedEventRecordScheme';
import { UserScheme } from './UserScheme';

const __base__EventSubmissionScheme=z.object({
});
const __lazy__EventSubmissionScheme=z.object({
    user:z.lazy(()=>UserScheme),
    events:z.lazy(()=>AddressedEventRecordScheme).array(),
});
export const EventSubmissionScheme:(typeof __base__EventSubmissionScheme)=__base__EventSubmissionScheme.merge(__lazy__EventSubmissionScheme) as any;
