/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventSubmission" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { AddressedEventRecord } from './AddressedEventRecord';
import { User } from './User';

export interface EventSubmission
{
    user:User;
    events:AddressedEventRecord[];
}
