/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CommsChannel } from './CommsChannel';

export interface EventRecord
{
    id:number;
    /**
     * Id of the user profile that triggered
     * the event
     */
    profileId?:number;
    /**
     * Client device id - Client generated uuid
     */
    cdi?:string;
    /**
     * Session Id - Client generated uuid
     */
    sid?:string;
    /**
     * Id of a product associated with the event
     */
    productId?:number;
    /**
     * Alternate product id
     */
    productAltId?:string;
    /**
     * Id of a location associated with the event
     */
    locationId?:number;
    /**
     * Alternate location id
     */
    locationAltId?:string;
    /**
     * Id of the account associated with the event
     */
    accountId?:number;
    messageId?:number;
    /**
     * The events type
     */
    type:string;
    /**
     * A timestamp of when the event occurred
     */
    time:number;
    data?:Record<string,any>;
    /**
     * Custom event data
     */
    importSource?:string;
    /**
     * A large unindexed string associated with the event
     */
    longText?:string;
    currencyValue?:number;
    /**
     * A short indexed string associated with the event
     */
    text?:string;
    /**
     * Array of tags that can be used to group events
     */
    tags?:string[];
    /**
     * URL path where the event occurred
     */
    path?:string;
    /**
     * Host / domain where the event occurred
     */
    host?:string;
    /**
     * Name of element associated with
     * the event. Mostly used with elemView
     * events
     */
    elem?:string;
    /**
     * List of classes of the element target triggered the event
     */
    classList?:string[];
    /**
     * Browser page x
     */
    x?:number;
    /**
     * Browser page y
     */
    y?:number;
    /**
     * Browser scroll x
     */
    sx?:number;
    /**
     * Browser scroll y
     */
    sy?:number;
    num?:number;
    str?:string;
    bool?:boolean;
    int?:number;
    /**
     * Campaign name. example - summer-sales or fall-discounts
     */
    utmCampaign?:string;
    /**
     * Where traffic is coming from for example - google or facebook
     */
    utmSource?:string;
    /**
     * What type of medium traffic is coming from.
     * example - sms, email, social, search
     */
    utmMedium?:string;
    /**
     * What type of content was interacted with.
     * example - image, nav-link, menu-link
     */
    utmContent?:string;
    /**
     * The copy the generated traffic. This will often be the tag
     * line of an ad.
     */
    utmTerm?:string;
    /**
     * IP address the event came from
     */
    ip?:string;
    lat?:number;
    lng?:number;
    postalCode?:string;
    city?:string;
    region?:string;
    state?:string;
    country?:string;
    formId?:number;
    submissionId?:number;
    automationId?:number;
    automationNodeId?:string;
    targetUrl?:string;
    channel?:CommsChannel;
}
