/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventUrlProxyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { EventUrlProxyRequest } from './EventUrlProxyRequest';

export interface invokeEventUrlProxyFnFunctionArgs
{
    input:EventUrlProxyRequest;
}
