/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventUrlProxyRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * In-order for the request to be accepted
 * a matching message record must be found
 * using the messageId and messageUuid.
 * Additional matching types maybe added
 * in the future
 */
export interface EventUrlProxyRequest
{
    url:string;
    /**
     * The event type that should be tracked
     */
    type:string;
    messageUuid?:string;
    messageId?:number;
    profileId?:number;
    profileUuid?:string;
    automationId?:string;
    automationNodeId?:string;
    /**
     * Event record defaults.
     */
    evt?:Record<string,any>;
    /**
     * The max number of events of the given event type
     * that should be recorded for a given profile
     */
    evtLimit?:number;
    /**
     * If true the contents of the URL should be
     * fetched and returned inline with the request.
     * If false a redirect to the url param is returned.
     */
    pipe?:boolean;
    /**
     * If defined the URL of the url proxy will be treated
     * like raw b64 data and pipe as the return as
     * the response of the request
     */
    urlB64ContentType?:string;
}
