/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventUrlProxyFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { EventUrlProxyRequestScheme } from './EventUrlProxyRequestScheme';

const __base__invokeEventUrlProxyFnFunctionArgsScheme=z.object({
});
const __lazy__invokeEventUrlProxyFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>EventUrlProxyRequestScheme),
});
export const invokeEventUrlProxyFnFunctionArgsScheme:(typeof __base__invokeEventUrlProxyFnFunctionArgsScheme)=__base__invokeEventUrlProxyFnFunctionArgsScheme.merge(__lazy__invokeEventUrlProxyFnFunctionArgsScheme) as any;
