/* <ALLOW_AUTO_DELETE DEPENDENCIES="EventRecord" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface EventRecord
{
    id:number;
    /**
     * Id of the user profile that triggered
     * the event
     */
    profileId?:number;
    /**
     * Id of a product associated with the event
     */
    productId?:number;
    /**
     * Alternate product id
     */
    productAltId?:string;
    /**
     * Id of a location associated with the event
     */
    locationId?:number;
    /**
     * Alternate location id
     */
    locationAltId?:string;
    /**
     * Id of the account associated with the event
     */
    accountId?:number;
    /**
     * The events type
     */
    type:string;
    /**
     * A timestamp of when the event occurred
     */
    time:number;
    /**
     * Custom event data
     */
    data?:Record<string,any>;
    /**
     * A large unindexed string associated with the event
     */
    longText?:string;
    /**
     * A short indexed string associated with the event
     */
    text?:string;
    /**
     * Array of tags that can be used to group events
     */
    tags?:string[];
    /**
     * URL path where the event occurred
     */
    path?:string;
    /**
     * Host / domain where the event occurred
     */
    host?:string;
    /**
     * Name of element associated with
     * the event. Mostly used with elemView
     * events
     */
    elem?:string;
    /**
     * List of classes of the element target triggered the event
     */
    classList?:string[];
    /**
     * Browser page x
     */
    x?:number;
    /**
     * Browser page y
     */
    y?:number;
    /**
     * Browser scroll x
     */
    sx?:number;
    /**
     * Browser scroll y
     */
    sy?:number;
}
