/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExecuteSelectSqlFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SqlSelectRequestScheme } from './SqlSelectRequestScheme';

const __base__invokeExecuteSelectSqlFnFunctionArgsScheme=z.object({
}).describe("Returns items selected by the raw SQL query. The user executing the sql only has access to a limited set of SQL tables");
const __lazy__invokeExecuteSelectSqlFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SqlSelectRequestScheme),
});
export const invokeExecuteSelectSqlFnFunctionArgsScheme:(typeof __base__invokeExecuteSelectSqlFnFunctionArgsScheme)=__base__invokeExecuteSelectSqlFnFunctionArgsScheme.merge(__lazy__invokeExecuteSelectSqlFnFunctionArgsScheme) as any;
