/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExecuteSelectQueryFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query } from './Query';

/**
 * Returns the items selected by the query
 */
export interface invokeExecuteSelectQueryFnFunctionArgs
{
    input:Query;
}
