/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExecuteSelectQueryFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryScheme } from './QueryScheme';

const __base__invokeExecuteSelectQueryFnFunctionArgsScheme=z.object({
}).describe("Returns the items selected by the query");
const __lazy__invokeExecuteSelectQueryFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>QueryScheme),
});
export const invokeExecuteSelectQueryFnFunctionArgsScheme:(typeof __base__invokeExecuteSelectQueryFnFunctionArgsScheme)=__base__invokeExecuteSelectQueryFnFunctionArgsScheme.merge(__lazy__invokeExecuteSelectQueryFnFunctionArgsScheme) as any;
