/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryFormat" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const ExportQueryFormatScheme=z.enum([
    "json",
    "csv",
]);
