/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ExportQueryRequestScheme } from './ExportQueryRequestScheme';

const __base__invokeExportQueryFnFunctionArgsScheme=z.object({
});
const __lazy__invokeExportQueryFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ExportQueryRequestScheme),
});
export const invokeExportQueryFnFunctionArgsScheme:(typeof __base__invokeExportQueryFnFunctionArgsScheme)=__base__invokeExportQueryFnFunctionArgsScheme.merge(__lazy__invokeExportQueryFnFunctionArgsScheme) as any;
