/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query } from './Query';

export interface ExportRecord
{
    id:number;
    uuid:string;
    currentIndex:number;
    offset:number;
    complete:boolean;
    query:Query;
}
