/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ExportStatus
{
    complete:boolean;
    urls:string[];
}
