/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryFormat" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "json",
    "csv"
] as const;
Object.freeze(unionAry);

export type ExportQueryFormat=typeof unionAry[number];

export const allExportQueryFormatAry:ExportQueryFormat[]=unionAry as any;
