/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ExportQueryRequest } from './ExportQueryRequest';

export interface invokeExportQueryFnFunctionArgs
{
    input:ExportQueryRequest;
}
