/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryScheme } from './QueryScheme';

const __base__ExportRecordScheme=z.object({
    id:z.number().int(),
    uuid:z.string().max(255),
    currentIndex:z.number().int(),
    offset:z.number().int(),
    complete:z.boolean(),
});
const __lazy__ExportRecordScheme=z.object({
    query:z.lazy(()=>QueryScheme),
});
export const ExportRecordScheme:(typeof __base__ExportRecordScheme)=__base__ExportRecordScheme.merge(__lazy__ExportRecordScheme) as any;
