/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ExportQueryFormatScheme } from './ExportQueryFormatScheme';
import { QueryScheme } from './QueryScheme';

const __base__ExportQueryRequestScheme=z.object({
    uuid:z.string().max(255),
});
const __lazy__ExportQueryRequestScheme=z.object({
    query:z.lazy(()=>QueryScheme),
    format:z.lazy(()=>ExportQueryFormatScheme),
});
export const ExportQueryRequestScheme:(typeof __base__ExportQueryRequestScheme)=__base__ExportQueryRequestScheme.merge(__lazy__ExportQueryRequestScheme) as any;
