/* <ALLOW_AUTO_DELETE DEPENDENCIES="ExportQueryRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ExportQueryFormat } from './ExportQueryFormat';
import type { Query } from './Query';

export interface ExportQueryRequest
{
    uuid:string;
    query:Query;
    format:ExportQueryFormat;
}
