/* <ALLOW_AUTO_DELETE DEPENDENCIES="FileSearchResult" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { FileSource } from './FileSource';

export interface FileSearchResult
{
    total:number;
    items:FileSource[];
}
