/* <ALLOW_AUTO_DELETE DEPENDENCIES="FileSearchResult" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { FileSourceScheme } from './FileSourceScheme';

const __base__FileSearchResultScheme=z.object({
    total:z.number().int(),
});
const __lazy__FileSearchResultScheme=z.object({
    items:z.lazy(()=>FileSourceScheme).array(),
});
export const FileSearchResultScheme:(typeof __base__FileSearchResultScheme)=__base__FileSearchResultScheme.merge(__lazy__FileSearchResultScheme) as any;
