/* <ALLOW_AUTO_DELETE DEPENDENCIES="FormDataItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface FormDataItem
{
    name:string;
    data:any;
    /**
     * Name of profile property to update
     */
    profileProp?:string;
}
