/* <ALLOW_AUTO_DELETE DEPENDENCIES="FormDataItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__FormDataItemScheme=z.object({
    name:z.string().max(255),
    data:z.any(),
    profileProp:z.string().max(255).optional().describe("Name of profile property to update"),
});
const __lazy__FormDataItemScheme=z.object({
});
export const FormDataItemScheme:(typeof __base__FormDataItemScheme)=__base__FormDataItemScheme.merge(__lazy__FormDataItemScheme) as any;
