/* <ALLOW_AUTO_DELETE DEPENDENCIES="FormSubmission" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { EventRecord } from './EventRecord';
import type { FormDataItem } from './FormDataItem';

export interface FormSubmission
{
    id:number;
    uuid:string;
    formId?:number;
    profileId?:number;
    profileUuid?:string;
    userId?:number;
    locationId?:number;
    created:number;
    /**
     * The URL where the submission was
     * submitted from
     */
    submissionUrl?:string;
    metadata?:any;
    step:number;
    data:FormDataItem[];
    events?:EventRecord[];
}
