/* <ALLOW_AUTO_DELETE DEPENDENCIES="FormDisplayType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "fullScreen",
    "popup",
    "embed"
] as const;
Object.freeze(unionAry);

export type FormDisplayType=typeof unionAry[number];

export const allFormDisplayTypeAry:FormDisplayType[]=unionAry as any;
