/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenericItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface GenericItem
{
    id:string;
    created:number;
    data:any;
    name?:string;
    type?:string;
}
