/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenericItem" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface GenericItem
{
    id:string;
    created:number;
    data:any;
    name?:string;
    type?:string;
}
