/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateImageRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface GenerateImageRequest
{
    description:string;
}
