/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateUserClaimsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Adds claims to tokens / JWTs generated
 * by Cognito
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeGenerateUserClaimsFnFunctionArgs
{
}
