/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateUserClaimsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGenerateUserClaimsFnFunctionArgsScheme=z.object({
}).describe("Adds claims to tokens / JWTs generated by Cognito");
const __lazy__invokeGenerateUserClaimsFnFunctionArgsScheme=z.object({
});
export const invokeGenerateUserClaimsFnFunctionArgsScheme:(typeof __base__invokeGenerateUserClaimsFnFunctionArgsScheme)=__base__invokeGenerateUserClaimsFnFunctionArgsScheme.merge(__lazy__invokeGenerateUserClaimsFnFunctionArgsScheme) as any;
