/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateImageRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__GenerateImageRequestScheme=z.object({
    description:z.string(),
});
const __lazy__GenerateImageRequestScheme=z.object({
});
export const GenerateImageRequestScheme:(typeof __base__GenerateImageRequestScheme)=__base__GenerateImageRequestScheme.merge(__lazy__GenerateImageRequestScheme) as any;
