/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateImageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { GenerateImageRequest } from './GenerateImageRequest';

export interface invokeGenerateImageFnFunctionArgs
{
    input:GenerateImageRequest;
}
