/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenericItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__GenericItemScheme=z.object({
    id:z.string().max(255),
    created:z.number(),
    data:z.any(),
    name:z.string().max(255).optional(),
    type:z.string().max(255).optional(),
});
const __lazy__GenericItemScheme=z.object({
});
export const GenericItemScheme:(typeof __base__GenericItemScheme)=__base__GenericItemScheme.merge(__lazy__GenericItemScheme) as any;
