/* <ALLOW_AUTO_DELETE DEPENDENCIES="GenerateImageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { GenerateImageRequestScheme } from './GenerateImageRequestScheme';

const __base__invokeGenerateImageFnFunctionArgsScheme=z.object({
});
const __lazy__invokeGenerateImageFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>GenerateImageRequestScheme),
});
export const invokeGenerateImageFnFunctionArgsScheme:(typeof __base__invokeGenerateImageFnFunctionArgsScheme)=__base__invokeGenerateImageFnFunctionArgsScheme.merge(__lazy__invokeGenerateImageFnFunctionArgsScheme) as any;
