/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetCurrentUserFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetCurrentUserFnFunctionArgsScheme=z.object({
}).describe("Returns a User object for the calling user. If no matching User is found in the Users table a new User is created.");
const __lazy__invokeGetCurrentUserFnFunctionArgsScheme=z.object({
});
export const invokeGetCurrentUserFnFunctionArgsScheme:(typeof __base__invokeGetCurrentUserFnFunctionArgsScheme)=__base__invokeGetCurrentUserFnFunctionArgsScheme.merge(__lazy__invokeGetCurrentUserFnFunctionArgsScheme) as any;
