/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetCurrentUserFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Returns a User object for the
 * calling user. If no matching User
 * is found in the Users table a new
 * User is created.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeGetCurrentUserFnFunctionArgs
{
}
