/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetDomainStatusFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetDomainStatusFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of domain to get status of"),
});
const __lazy__invokeGetDomainStatusFnFunctionArgsScheme=z.object({
});
export const invokeGetDomainStatusFnFunctionArgsScheme:(typeof __base__invokeGetDomainStatusFnFunctionArgsScheme)=__base__invokeGetDomainStatusFnFunctionArgsScheme.merge(__lazy__invokeGetDomainStatusFnFunctionArgsScheme) as any;
