/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetDomainStatusFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeGetDomainStatusFnFunctionArgs
{
    /**
     * Id of domain to get status of
     */
    input:number;
}
