/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetExportStatusFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetExportStatusFnFunctionArgsScheme=z.object({
    input:z.string().max(255),
});
const __lazy__invokeGetExportStatusFnFunctionArgsScheme=z.object({
});
export const invokeGetExportStatusFnFunctionArgsScheme:(typeof __base__invokeGetExportStatusFnFunctionArgsScheme)=__base__invokeGetExportStatusFnFunctionArgsScheme.merge(__lazy__invokeGetExportStatusFnFunctionArgsScheme) as any;
