/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetExportStatusFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeGetExportStatusFnFunctionArgs
{
    input:string;
}
