/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetFormsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetFormsFnFunctionArgsScheme=z.object({
});
const __lazy__invokeGetFormsFnFunctionArgsScheme=z.object({
});
export const invokeGetFormsFnFunctionArgsScheme:(typeof __base__invokeGetFormsFnFunctionArgsScheme)=__base__invokeGetFormsFnFunctionArgsScheme.merge(__lazy__invokeGetFormsFnFunctionArgsScheme) as any;
