/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetLocationInfoFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeGetLocationInfoFnFunctionArgs
{
}
