/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetLocationInfoFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetLocationInfoFnFunctionArgsScheme=z.object({
});
const __lazy__invokeGetLocationInfoFnFunctionArgsScheme=z.object({
});
export const invokeGetLocationInfoFnFunctionArgsScheme:(typeof __base__invokeGetLocationInfoFnFunctionArgsScheme)=__base__invokeGetLocationInfoFnFunctionArgsScheme.merge(__lazy__invokeGetLocationInfoFnFunctionArgsScheme) as any;
