/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetMessageStatusRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__GetMessageStatusRequestScheme=z.object({
    messageId:z.string().max(255),
});
const __lazy__GetMessageStatusRequestScheme=z.object({
});
export const GetMessageStatusRequestScheme:(typeof __base__GetMessageStatusRequestScheme)=__base__GetMessageStatusRequestScheme.merge(__lazy__GetMessageStatusRequestScheme) as any;
