/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetMessageStatusRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface GetMessageStatusRequest
{
    messageId:string;
}
