/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetMessageStatusFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { GetMessageStatusRequestScheme } from './GetMessageStatusRequestScheme';

const __base__invokeGetMessageStatusFnFunctionArgsScheme=z.object({
});
const __lazy__invokeGetMessageStatusFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>GetMessageStatusRequestScheme),
});
export const invokeGetMessageStatusFnFunctionArgsScheme:(typeof __base__invokeGetMessageStatusFnFunctionArgsScheme)=__base__invokeGetMessageStatusFnFunctionArgsScheme.merge(__lazy__invokeGetMessageStatusFnFunctionArgsScheme) as any;
