/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetMessageStatusFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { GetMessageStatusRequest } from './GetMessageStatusRequest';

export interface invokeGetMessageStatusFnFunctionArgs
{
    input:GetMessageStatusRequest;
}
