/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetQueryRecords" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeGetQueryRecordsFunctionArgsScheme=z.object({
}).describe("Returns all query records for the calling user");
const __lazy__invokeGetQueryRecordsFunctionArgsScheme=z.object({
});
export const invokeGetQueryRecordsFunctionArgsScheme:(typeof __base__invokeGetQueryRecordsFunctionArgsScheme)=__base__invokeGetQueryRecordsFunctionArgsScheme.merge(__lazy__invokeGetQueryRecordsFunctionArgsScheme) as any;
