/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetQueryRecords" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Returns all query records for the calling user
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeGetQueryRecordsFunctionArgs
{
}
