/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetShopifyUserStatusFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { UserScheme } from './UserScheme';

const __base__invokeGetShopifyUserStatusFnFunctionArgsScheme=z.object({
});
const __lazy__invokeGetShopifyUserStatusFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>UserScheme),
});
export const invokeGetShopifyUserStatusFnFunctionArgsScheme:(typeof __base__invokeGetShopifyUserStatusFnFunctionArgsScheme)=__base__invokeGetShopifyUserStatusFnFunctionArgsScheme.merge(__lazy__invokeGetShopifyUserStatusFnFunctionArgsScheme) as any;
