/* <ALLOW_AUTO_DELETE DEPENDENCIES="GetShopifyUserStatusFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { User } from './User';

export interface invokeGetShopifyUserStatusFnFunctionArgs
{
    input:User;
}
