/* <ALLOW_AUTO_DELETE DEPENDENCIES="GroupMessageSendTarget" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryScheme } from './QueryScheme';

const __base__GroupMessageSendTargetScheme=z.object({
    groupId:z.number().optional().describe("Segment or list id"),
    orderBy:z.string().max(255).optional(),
    orderByDesc:z.boolean().optional(),
    offset:z.number().optional(),
    limit:z.number().optional(),
});
const __lazy__GroupMessageSendTargetScheme=z.object({
    query:z.lazy(()=>QueryScheme).optional(),
});
export const GroupMessageSendTargetScheme:(typeof __base__GroupMessageSendTargetScheme)=__base__GroupMessageSendTargetScheme.merge(__lazy__GroupMessageSendTargetScheme) as any;
