/* <ALLOW_AUTO_DELETE DEPENDENCIES="GroupMessageSendTarget" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query } from './Query';

export interface GroupMessageSendTarget
{
    /**
     * Segment or list id
     */
    groupId?:number;
    orderBy?:string;
    orderByDesc?:boolean;
    offset?:number;
    limit?:number;
    query?:Query;
}
