/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportListFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ImportListRequestScheme } from './ImportListRequestScheme';

const __base__invokeImportListFnFunctionArgsScheme=z.object({
});
const __lazy__invokeImportListFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ImportListRequestScheme).describe("CSV File"),
});
export const invokeImportListFnFunctionArgsScheme:(typeof __base__invokeImportListFnFunctionArgsScheme)=__base__invokeImportListFnFunctionArgsScheme.merge(__lazy__invokeImportListFnFunctionArgsScheme) as any;
