/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportFileRecordUrlsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeImportFileRecordUrlsFnFunctionArgs
{
    /**
     * Id of the FileRecord to import URLs for
     */
    input:number;
}
