/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportFileRecordUrlsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeImportFileRecordUrlsFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of the FileRecord to import URLs for"),
});
const __lazy__invokeImportFileRecordUrlsFnFunctionArgsScheme=z.object({
});
export const invokeImportFileRecordUrlsFnFunctionArgsScheme:(typeof __base__invokeImportFileRecordUrlsFnFunctionArgsScheme)=__base__invokeImportFileRecordUrlsFnFunctionArgsScheme.merge(__lazy__invokeImportFileRecordUrlsFnFunctionArgsScheme) as any;
