/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportListRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ImportListRequestScheme=z.object({
    listId:z.number().int().optional(),
    name:z.string().max(255).optional(),
    csv:z.string().optional(),
    json:z.any().array().optional(),
    propMap:z.record(z.any()).optional(),
    profileIds:z.number().int().array().optional(),
});
const __lazy__ImportListRequestScheme=z.object({
});
export const ImportListRequestScheme:(typeof __base__ImportListRequestScheme)=__base__ImportListRequestScheme.merge(__lazy__ImportListRequestScheme) as any;
