/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportListFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ImportListRequest } from './ImportListRequest';

export interface invokeImportListFnFunctionArgs
{
    /**
     * CSV File
     */
    input:ImportListRequest;
}
