/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportProfileFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ProfileScheme } from './ProfileScheme';

const __base__invokeImportProfileFnFunctionArgsScheme=z.object({
});
const __lazy__invokeImportProfileFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ProfileScheme),
});
export const invokeImportProfileFnFunctionArgsScheme:(typeof __base__invokeImportProfileFnFunctionArgsScheme)=__base__invokeImportProfileFnFunctionArgsScheme.merge(__lazy__invokeImportProfileFnFunctionArgsScheme) as any;
