/* <ALLOW_AUTO_DELETE DEPENDENCIES="ImportListRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ImportListRequest
{
    listId?:number;
    name?:string;
    csv?:string;
    json?:any[];
    propMap?:Record<string,any>;
    profileIds?:number[];
}
