/* <ALLOW_AUTO_DELETE DEPENDENCIES="InputType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "text",
    "email",
    "phone",
    "number",
    "radioGroup",
    "checkbox",
    "dropdown",
    "date"
] as const;
Object.freeze(unionAry);

export type InputType=typeof unionAry[number];

export const allInputTypeAry:InputType[]=unionAry as any;
