/* <ALLOW_AUTO_DELETE DEPENDENCIES="LayoutAxis" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "x",
    "y"
] as const;
Object.freeze(unionAry);

export type LayoutAxis=typeof unionAry[number];

export const allLayoutAxisAry:LayoutAxis[]=unionAry as any;
