/* <ALLOW_AUTO_DELETE DEPENDENCIES="LayoutAlignment" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const LayoutAlignmentScheme=z.enum([
    "start",
    "center",
    "end",
]);
