/* <ALLOW_AUTO_DELETE DEPENDENCIES="LayoutAxis" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const LayoutAxisScheme=z.enum([
    "x",
    "y",
]);
