/* <ALLOW_AUTO_DELETE DEPENDENCIES="LayoutAlignment" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "start",
    "center",
    "end"
] as const;
Object.freeze(unionAry);

export type LayoutAlignment=typeof unionAry[number];

export const allLayoutAlignmentAry:LayoutAlignment[]=unionAry as any;
