/* <ALLOW_AUTO_DELETE DEPENDENCIES="Location" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { Profile } from './Profile';
import { EventRecord } from './EventRecord';

/**
 * Can either be a physical or digital location
 */
export interface Location
{
    id:number;
    regionId?:number;
    accountId?:number;
    name?:string;
    email?:string;
    domain?:string;
    phone?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    events?:EventRecord[];
    profiles?:Profile[];
}
