/* <ALLOW_AUTO_DELETE DEPENDENCIES="Location" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { FormSubmissionScheme } from './FormSubmissionScheme';
import { ProfileScheme } from './ProfileScheme';
import { EventRecordScheme } from './EventRecordScheme';

const __base__LocationScheme=z.object({
    id:z.number().int(),
    regionId:z.number().int().optional(),
    accountId:z.number().int().optional(),
    created:z.number().optional(),
    name:z.string().max(255).optional(),
    email:z.string().email().optional(),
    domain:z.string().max(255).optional(),
    phone:z.string().max(255).optional(),
    country:z.string().max(255).optional(),
    state:z.string().max(255).optional(),
    city:z.string().max(255).optional(),
    address:z.string().max(255).optional(),
    address2:z.string().max(255).optional(),
    postalCode:z.string().max(255).optional(),
}).describe("Can either be a physical or digital location");
const __lazy__LocationScheme=z.object({
    events:z.lazy(()=>EventRecordScheme).array().optional(),
    profiles:z.lazy(()=>ProfileScheme).array().optional(),
    formSubmissions:z.lazy(()=>FormSubmissionScheme).array().optional(),
});
export const LocationScheme:(typeof __base__LocationScheme)=__base__LocationScheme.merge(__lazy__LocationScheme) as any;
