/* <ALLOW_AUTO_DELETE DEPENDENCIES="LocationInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__LocationInfoScheme=z.object({
    ip:z.string().max(255).optional(),
    lat:z.number().optional(),
    lng:z.number().optional(),
    postalCode:z.string().max(255).optional(),
    city:z.string().max(255).optional(),
    region:z.string().max(255).optional(),
    country:z.string().max(255).optional(),
});
const __lazy__LocationInfoScheme=z.object({
});
export const LocationInfoScheme:(typeof __base__LocationInfoScheme)=__base__LocationInfoScheme.merge(__lazy__LocationInfoScheme) as any;
