/* <ALLOW_AUTO_DELETE DEPENDENCIES="LocationInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface LocationInfo
{
    ip?:string;
    lat?:number;
    lng?:number;
    postalCode?:string;
    city?:string;
    region?:string;
    country?:string;
}
