/* <ALLOW_AUTO_DELETE DEPENDENCIES="Location" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { FormSubmission } from './FormSubmission';
import type { Profile } from './Profile';
import type { EventRecord } from './EventRecord';

/**
 * Can either be a physical or digital location
 */
export interface Location
{
    id:number;
    regionId?:number;
    accountId?:number;
    created?:number;
    name?:string;
    email?:string;
    domain?:string;
    phone?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    events?:EventRecord[];
    profiles?:Profile[];
    formSubmissions?:FormSubmission[];
}
