/* <ALLOW_AUTO_DELETE DEPENDENCIES="LogoUploadFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeLogoUploadFnFunctionArgsScheme=z.object({
    input:z.string().max(255),
});
const __lazy__invokeLogoUploadFnFunctionArgsScheme=z.object({
});
export const invokeLogoUploadFnFunctionArgsScheme:(typeof __base__invokeLogoUploadFnFunctionArgsScheme)=__base__invokeLogoUploadFnFunctionArgsScheme.merge(__lazy__invokeLogoUploadFnFunctionArgsScheme) as any;
