/* <ALLOW_AUTO_DELETE DEPENDENCIES="MarketingFeature" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface MarketingFeature
{
    name?:string;
}
