/* <ALLOW_AUTO_DELETE DEPENDENCIES="MarketingFeature" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__MarketingFeatureScheme=z.object({
    name:z.string().max(255).optional(),
});
const __lazy__MarketingFeatureScheme=z.object({
});
export const MarketingFeatureScheme:(typeof __base__MarketingFeatureScheme)=__base__MarketingFeatureScheme.merge(__lazy__MarketingFeatureScheme) as any;
