/* <ALLOW_AUTO_DELETE DEPENDENCIES="MediaSize" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const MediaSizeScheme=z.enum([
    "src",
    "sm",
    "md",
    "lg",
]);
