/* <ALLOW_AUTO_DELETE DEPENDENCIES="MediaSize" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "src",
    "sm",
    "md",
    "lg"
] as const;
Object.freeze(unionAry);

export type MediaSize=typeof unionAry[number];

export const allMediaSizeAry:MediaSize[]=unionAry as any;
