/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageDelivery" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { MessageTarget } from './MessageTarget';

export interface MessageDelivery
{
    id:number;
    created:number;
    templateId:number;
    accountId?:number;
    targets?:MessageTarget[];
}
