/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageDelivery" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { MessageTargetScheme } from './MessageTargetScheme';

const __base__MessageDeliveryScheme=z.object({
    id:z.number().int(),
    created:z.number(),
    templateId:z.number().int(),
    accountId:z.number().int().optional(),
});
const __lazy__MessageDeliveryScheme=z.object({
    targets:z.lazy(()=>MessageTargetScheme).array().optional(),
});
export const MessageDeliveryScheme:(typeof __base__MessageDeliveryScheme)=__base__MessageDeliveryScheme.merge(__lazy__MessageDeliveryScheme) as any;
