/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageRenderTarget" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "browser",
    "email",
    "text"
] as const;
Object.freeze(unionAry);

export type MessageRenderTarget=typeof unionAry[number];

export const allMessageRenderTargetAry:MessageRenderTarget[]=unionAry as any;
