/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageChannel" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type MessageChannel=(
    "email"|
    "phone"|
    "push"
);
