/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const MessageTypeScheme=z.enum([
    "email",
    "emailText",
    "sms",
    "notification",
]);
