/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageTemplate" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { TemplateModel } from './TemplateModel';
import type { MessageRecord } from './MessageRecord';
import type { CommsChannel } from './CommsChannel';

export interface MessageTemplate
{
    /**
     * If not storing in the database use an id of 0
     */
    id:number;
    uuid?:string;
    name?:string;
    created?:number;
    lastUpdated?:number;
    subject?:string;
    accountId?:number;
    iconUrl?:string;
    published?:boolean;
    tags?:string[];
    previewText?:string;
    /**
     * If not set the default sender will be used
     */
    senderId?:number;
    isDraft?:boolean;
    /**
     * Id of a message template that this message
     * template is a draft of
     */
    publishId?:number;
    /**
     * Id of a message template that this message
     * template is a published version of
     */
    draftId?:number;
    customUnsubscribeLink?:string;
    trackingEnabled?:boolean;
    includePlatformBranding?:boolean;
    /**
     * If true the template can be used as an embed
     * and embedded in other templates
     */
    isEmbed?:boolean;
    /**
     * Header, footer, etc
     */
    embedType?:string;
    disableEmail?:boolean;
    disableSms?:boolean;
    disableNotification?:boolean;
    preferredChannel?:CommsChannel;
    messages?:MessageRecord[];
    emailTemplateModel?:TemplateModel;
    emailTextTemplateModel?:TemplateModel;
    smsTemplateModel?:TemplateModel;
    notiticationTemplateModel?:TemplateModel;
    textTemplateModel?:TemplateModel;
    formTemplateModel?:TemplateModel;
}
