/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageSender" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageTemplate } from './MessageTemplate';
import type { MessageRecord } from './MessageRecord';

export interface MessageSender
{
    id:number;
    isDefault?:boolean;
    name?:string;
    email?:string;
    emailVerified?:boolean;
    phone?:string;
    phoneVerified?:boolean;
    website?:string;
    accountId?:number;
    created?:number;
    /**
     * Web Push params
     */
    vapid?:Record<string,any>;
    messages?:MessageRecord[];
    messageTemplates?:MessageTemplate[];
}
