/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageSender" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { MessageTemplate } from './MessageTemplate';

export interface MessageSender
{
    id:number;
    isDefault?:boolean;
    name?:string;
    email?:string;
    emailVerified?:boolean;
    phone?:string;
    phoneVerified?:boolean;
    website?:string;
    accountId?:number;
    messageTemplates?:MessageTemplate[];
}
