/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageRenderTarget" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const MessageRenderTargetScheme=z.enum([
    "browser",
    "email",
    "text",
]);
