/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageChannel" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const MessageChannelScheme=z.enum([
    "email",
    "phone",
    "push",
]);
