/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type MessageType=(
    "email"|
    "emailText"|
    "sms"|
    "notification"
);
