/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageTemplate" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { MessageDeliveryScheme } from './MessageDeliveryScheme';
import { MessageTypeScheme } from './MessageTypeScheme';

const __base__MessageTemplateScheme=z.object({
    id:z.number().int(),
    name:z.string().max(255).optional(),
    created:z.number().optional(),
    subject:z.string().max(255).optional(),
    accountId:z.number().int().optional(),
    iconUrl:z.string().max(255).optional(),
    published:z.boolean().optional(),
    body:z.record(z.any()).optional(),
    tags:z.string().max(255).array().optional(),
    previewText:z.string().optional(),
    senderId:z.number().int(),
    customUnsubscribeLink:z.string().optional(),
    trackingEnabled:z.boolean().optional(),
    includePlatformBranding:z.boolean().optional(),
});
const __lazy__MessageTemplateScheme=z.object({
    type:z.lazy(()=>MessageTypeScheme),
    deliveries:z.lazy(()=>MessageDeliveryScheme).array().optional(),
});
export const MessageTemplateScheme:(typeof __base__MessageTemplateScheme)=__base__MessageTemplateScheme.merge(__lazy__MessageTemplateScheme) as any;
