/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageTemplate" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { MessageDelivery } from './MessageDelivery';
import { MessageType } from './MessageType';

export interface MessageTemplate
{
    id:number;
    name?:string;
    created?:number;
    subject?:string;
    accountId?:number;
    iconUrl?:string;
    published?:boolean;
    body?:Record<string,any>;
    tags?:string[];
    previewText?:string;
    senderId:number;
    customUnsubscribeLink?:string;
    trackingEnabled?:boolean;
    includePlatformBranding?:boolean;
    type:MessageType;
    deliveries?:MessageDelivery[];
}
