/* <ALLOW_AUTO_DELETE DEPENDENCIES="MessageTarget" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface MessageTarget
{
    id:number;
    deliveryId:number;
    email?:string;
    phone?:string;
    deviceId?:number;
    profileId?:number;
    userId?:number;
}
