/* <ALLOW_AUTO_DELETE DEPENDENCIES="NewUserCreatedEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { User } from './User';

export interface NewUserCreatedEvent
{
    user:User;
}
