/* <ALLOW_AUTO_DELETE DEPENDENCIES="NotificationDevice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MessageRecordScheme } from './MessageRecordScheme';

const __base__NotificationDeviceScheme=z.object({
    id:z.number().int(),
    profileId:z.number().int().optional(),
    userId:z.number().int().optional(),
    created:z.number().optional(),
    pushEndpoint:z.string().max(255).optional(),
    pushSubscription:z.record(z.any()).optional(),
});
const __lazy__NotificationDeviceScheme=z.object({
    messages:z.lazy(()=>MessageRecordScheme).array().optional(),
});
export const NotificationDeviceScheme:(typeof __base__NotificationDeviceScheme)=__base__NotificationDeviceScheme.merge(__lazy__NotificationDeviceScheme) as any;
