/* <ALLOW_AUTO_DELETE DEPENDENCIES="NotificationDevice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageRecord } from './MessageRecord';

export interface NotificationDevice
{
    id:number;
    profileId?:number;
    userId?:number;
    created?:number;
    pushEndpoint?:string;
    pushSubscription?:Record<string,any>;
    messages?:MessageRecord[];
}
