/* <ALLOW_AUTO_DELETE DEPENDENCIES="NotificationDevice" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { MessageTarget } from './MessageTarget';

export interface NotificationDevice
{
    id:number;
    profileId?:number;
    userId?:number;
    targetedMessages?:MessageTarget[];
}
