/* <ALLOW_AUTO_DELETE DEPENDENCIES="Price" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripePriceTypeScheme } from './StripePriceTypeScheme';
import { RecurringPriceScheme } from './RecurringPriceScheme';

const __base__PriceScheme=z.object({
    currency:z.string().max(255).optional(),
    unitAmount:z.number(),
    id:z.string().max(255),
});
const __lazy__PriceScheme=z.object({
    recurring:z.lazy(()=>RecurringPriceScheme).optional(),
    type:z.lazy(()=>StripePriceTypeScheme),
});
export const PriceScheme:(typeof __base__PriceScheme)=__base__PriceScheme.merge(__lazy__PriceScheme) as any;
