/* <ALLOW_AUTO_DELETE DEPENDENCIES="Price" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripePriceType } from './StripePriceType';
import type { RecurringPrice } from './RecurringPrice';

export interface Price
{
    currency?:string;
    unitAmount:number;
    id:string;
    recurring?:RecurringPrice;
    type:StripePriceType;
}
