/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProcessEventsAsync" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { EventSubmission } from './EventSubmission';

export interface ProcessEventsAsyncFunctionArgs
{
    callMap:any;
    submission:EventSubmission;
}
