/* <ALLOW_AUTO_DELETE DEPENDENCIES="Product" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { EventRecord } from './EventRecord';

export interface Product
{
    id:number;
    altId?:string;
    name:string;
    price:number;
    created?:number;
    events?:EventRecord[];
}
