/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileResolveRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ProfileInfoScheme } from './ProfileInfoScheme';

const __base__ProfileResolveRequestScheme=z.object({
    profileId:z.number().int().optional().describe("profileId is ignored by public endpoints"),
    deviceUuid:z.string().max(255).optional(),
    profileUuid:z.string().max(255).optional(),
    sessionUuid:z.string().max(255).optional(),
    remoteAddress:z.string().max(255).optional(),
    autoCreateProfile:z.boolean().optional(),
    identificationSource:z.string().max(255).optional(),
});
const __lazy__ProfileResolveRequestScheme=z.object({
    profileInfo:z.lazy(()=>ProfileInfoScheme).optional(),
});
export const ProfileResolveRequestScheme:(typeof __base__ProfileResolveRequestScheme)=__base__ProfileResolveRequestScheme.merge(__lazy__ProfileResolveRequestScheme) as any;
