/* <ALLOW_AUTO_DELETE DEPENDENCIES="Profile" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ProfileDevice } from './ProfileDevice';
import type { FormSubmission } from './FormSubmission';
import type { CommsChannel } from './CommsChannel';
import type { ProfileGroupPlacement } from './ProfileGroupPlacement';
import type { MessageRecord } from './MessageRecord';
import type { NotificationDevice } from './NotificationDevice';
import type { SubscriptionStatus } from './SubscriptionStatus';
import type { EventRecord } from './EventRecord';
import type { ProfileStatus } from './ProfileStatus';

export interface Profile
{
    id:number;
    altId?:string;
    uuid?:string;
    accountId?:number;
    importId?:string;
    importBatchId?:string;
    name?:string;
    firstName?:string;
    middleName?:string;
    lastName?:string;
    email?:string;
    website?:string;
    created?:number;
    lastActivity?:number;
    timezone?:string;
    phone?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    birthDate?:number;
    identificationSource?:string;
    smsIdentificationSource?:string;
    identifiedAt?:number;
    smsIdentifiedAt?:number;
    notificationIdentifiedAt?:number;
    identListId?:number;
    identFormId?:number;
    data?:Record<string,any>;
    /**
     * Usually the store the profile is associated with
     */
    primaryLocationId?:number;
    jobTitle?:string;
    company?:string;
    department?:string;
    pStat:ProfileStatus;
    events?:EventRecord[];
    status:SubscriptionStatus;
    smsStatus:SubscriptionStatus;
    notificationStatus:SubscriptionStatus;
    notificationDevices?:NotificationDevice[];
    messages?:MessageRecord[];
    groupPlacements?:ProfileGroupPlacement[];
    preferredChannel?:CommsChannel;
    formSubmissions?:FormSubmission[];
    devices?:ProfileDevice[];
}
