/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroupType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const ProfileGroupTypeScheme=z.enum([
    "list",
    "audience",
]);
