/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileLookup" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { LocationInfo } from './LocationInfo';
import type { ProfileInfo } from './ProfileInfo';

export interface ProfileLookup
{
    profile?:ProfileInfo;
    location?:LocationInfo;
}
