/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * 
 * - disabled - Does not appear in analytics by default and
 *   can not receive messages.
 * 
 * - active - Fully enabled.
 * 
 * - suppressed - Appears in analytics but do not receive
 *   messages. If a suppressed profile submits
 *   an event the profile made active.
 */
export enum ProfileStatus{
    disabled=0,
    active=1,
    suppressed=2,
}
