/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileDevice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ProfileDeviceScheme=z.object({
    id:z.number().int(),
    profileId:z.number().int().optional(),
    uuid:z.string().max(255),
    created:z.number(),
    agentString:z.string().optional(),
});
const __lazy__ProfileDeviceScheme=z.object({
});
export const ProfileDeviceScheme:(typeof __base__ProfileDeviceScheme)=__base__ProfileDeviceScheme.merge(__lazy__ProfileDeviceScheme) as any;
