/* <ALLOW_AUTO_DELETE DEPENDENCIES="Profile" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { ProfileGroupPlacementScheme } from './ProfileGroupPlacementScheme';
import { MessageTargetScheme } from './MessageTargetScheme';
import { NotificationDeviceScheme } from './NotificationDeviceScheme';
import { SubscriptionStatusScheme } from './SubscriptionStatusScheme';
import { EventRecordScheme } from './EventRecordScheme';
import { WorkerScheme } from './WorkerScheme';

const __base__ProfileScheme=z.object({
    id:z.number().int(),
    accountId:z.number().int().optional(),
    name:z.string().max(255).optional(),
    firstName:z.string().max(255).optional(),
    middleName:z.string().max(255).optional(),
    lastName:z.string().max(255).optional(),
    email:z.string().email().optional(),
    website:z.string().max(255).optional(),
    created:z.number().optional(),
    lastActivity:z.number().optional(),
    timezone:z.string().max(255).optional(),
    phone:z.string().max(255).optional(),
    country:z.string().max(255).optional(),
    state:z.string().max(255).optional(),
    city:z.string().max(255).optional(),
    address:z.string().max(255).optional(),
    address2:z.string().max(255).optional(),
    postalCode:z.string().max(255).optional(),
    birthDate:z.number().optional(),
    identificationSource:z.string().max(255).optional(),
    data:z.record(z.any()).optional(),
    primaryLocationId:z.number().int().optional().describe("Usually the store the profile is associated with"),
});
const __lazy__ProfileScheme=z.object({
    workers:z.lazy(()=>WorkerScheme).array().optional(),
    events:z.lazy(()=>EventRecordScheme).array().optional(),
    status:z.lazy(()=>SubscriptionStatusScheme),
    notificationDevices:z.lazy(()=>NotificationDeviceScheme).array().optional(),
    targetedMessages:z.lazy(()=>MessageTargetScheme).array().optional(),
    groupPlacements:z.lazy(()=>ProfileGroupPlacementScheme).array().optional(),
});
export const ProfileScheme:(typeof __base__ProfileScheme)=__base__ProfileScheme.merge(__lazy__ProfileScheme) as any;
