/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroup" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { ProfileGroupPlacement } from './ProfileGroupPlacement';
import { ProfileGroupType } from './ProfileGroupType';

/**
 * Represents an audience or list of profiles.
 * Profile groups consists of profiles included by the
 * the groups query and by profiles that are directly
 * placed in the group via ProfileGroupPlacement records.
 */
export interface ProfileGroup
{
    id:number;
    name?:string;
    description?:string;
    query?:Record<string,any>;
    lastUserCount?:number;
    type:ProfileGroupType;
    placedProfiles?:ProfileGroupPlacement[];
}
