/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileDevice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ProfileDevice
{
    id:number;
    profileId?:number;
    uuid:string;
    created:number;
    agentString?:string;
}
