/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileLookup" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { LocationInfoScheme } from './LocationInfoScheme';
import { ProfileInfoScheme } from './ProfileInfoScheme';

const __base__ProfileLookupScheme=z.object({
});
const __lazy__ProfileLookupScheme=z.object({
    profile:z.lazy(()=>ProfileInfoScheme).optional(),
    location:z.lazy(()=>LocationInfoScheme).optional(),
});
export const ProfileLookupScheme:(typeof __base__ProfileLookupScheme)=__base__ProfileLookupScheme.merge(__lazy__ProfileLookupScheme) as any;
