/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { SubscriptionStatus } from './SubscriptionStatus';
import type { ProfileStatus } from './ProfileStatus';

export interface ProfileInfo
{
    id:number;
    uuid:string;
    name?:string;
    firstName?:string;
    lastName?:string;
    email?:string;
    phone?:string;
    pStat:ProfileStatus;
    status:SubscriptionStatus;
}
