/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroupPlacement" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ProfileGroupPlacementScheme=z.object({
    id:z.number().int(),
    created:z.number(),
    disabledAt:z.number().optional().describe("The time when the profile placement was disabled.\nFor historical purposes profile placements are never deleted they are only disabled."),
    profileId:z.number().int(),
    groupId:z.number().int(),
});
const __lazy__ProfileGroupPlacementScheme=z.object({
});
export const ProfileGroupPlacementScheme:(typeof __base__ProfileGroupPlacementScheme)=__base__ProfileGroupPlacementScheme.merge(__lazy__ProfileGroupPlacementScheme) as any;
