/* <ALLOW_AUTO_DELETE DEPENDENCIES="Profile" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ProfileDeviceScheme } from './ProfileDeviceScheme';
import { FormSubmissionScheme } from './FormSubmissionScheme';
import { CommsChannelScheme } from './CommsChannelScheme';
import { ProfileGroupPlacementScheme } from './ProfileGroupPlacementScheme';
import { MessageRecordScheme } from './MessageRecordScheme';
import { NotificationDeviceScheme } from './NotificationDeviceScheme';
import { SubscriptionStatusScheme } from './SubscriptionStatusScheme';
import { EventRecordScheme } from './EventRecordScheme';
import { ProfileStatusScheme } from './ProfileStatusScheme';

const __base__ProfileScheme=z.object({
    id:z.number().int(),
    altId:z.string().max(255).optional(),
    uuid:z.string().max(255).optional(),
    accountId:z.number().int().optional(),
    importId:z.string().max(255).optional(),
    importBatchId:z.string().max(255).optional(),
    name:z.string().max(255).optional(),
    firstName:z.string().max(255).optional(),
    middleName:z.string().max(255).optional(),
    lastName:z.string().max(255).optional(),
    email:z.string().email().optional(),
    website:z.string().max(255).optional(),
    created:z.number().optional(),
    lastActivity:z.number().optional(),
    timezone:z.string().max(255).optional(),
    phone:z.string().max(255).optional(),
    country:z.string().max(255).optional(),
    state:z.string().max(255).optional(),
    city:z.string().max(255).optional(),
    address:z.string().max(255).optional(),
    address2:z.string().max(255).optional(),
    postalCode:z.string().max(255).optional(),
    birthDate:z.number().optional(),
    identificationSource:z.string().max(255).optional(),
    smsIdentificationSource:z.string().max(255).optional(),
    identifiedAt:z.number().optional(),
    smsIdentifiedAt:z.number().optional(),
    notificationIdentifiedAt:z.number().optional(),
    identListId:z.number().int().optional(),
    identFormId:z.number().int().optional(),
    data:z.record(z.any()).optional(),
    primaryLocationId:z.number().int().optional().describe("Usually the store the profile is associated with"),
    jobTitle:z.string().max(255).optional(),
    company:z.string().max(255).optional(),
    department:z.string().max(255).optional(),
});
const __lazy__ProfileScheme=z.object({
    pStat:z.lazy(()=>ProfileStatusScheme),
    events:z.lazy(()=>EventRecordScheme).array().optional(),
    status:z.lazy(()=>SubscriptionStatusScheme),
    smsStatus:z.lazy(()=>SubscriptionStatusScheme),
    notificationStatus:z.lazy(()=>SubscriptionStatusScheme),
    notificationDevices:z.lazy(()=>NotificationDeviceScheme).array().optional(),
    messages:z.lazy(()=>MessageRecordScheme).array().optional(),
    groupPlacements:z.lazy(()=>ProfileGroupPlacementScheme).array().optional(),
    preferredChannel:z.lazy(()=>CommsChannelScheme).optional(),
    formSubmissions:z.lazy(()=>FormSubmissionScheme).array().optional(),
    devices:z.lazy(()=>ProfileDeviceScheme).array().optional(),
});
export const ProfileScheme:(typeof __base__ProfileScheme)=__base__ProfileScheme.merge(__lazy__ProfileScheme) as any;
