/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroupType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "list",
    "audience"
] as const;
Object.freeze(unionAry);

export type ProfileGroupType=typeof unionAry[number];

export const allProfileGroupTypeAry:ProfileGroupType[]=unionAry as any;
