/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SubscriptionStatusScheme } from './SubscriptionStatusScheme';
import { ProfileStatusScheme } from './ProfileStatusScheme';

const __base__ProfileInfoScheme=z.object({
    id:z.number().int(),
    uuid:z.string().max(255),
    name:z.string().max(255).optional(),
    firstName:z.string().max(255).optional(),
    lastName:z.string().max(255).optional(),
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
});
const __lazy__ProfileInfoScheme=z.object({
    pStat:z.lazy(()=>ProfileStatusScheme),
    status:z.lazy(()=>SubscriptionStatusScheme),
});
export const ProfileInfoScheme:(typeof __base__ProfileInfoScheme)=__base__ProfileInfoScheme.merge(__lazy__ProfileInfoScheme) as any;
