/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const ProfileStatusScheme=z.number().int().describe("\n- disabled - Does not appear in analytics by default and\n   can not receive messages.\n\n- active - Fully enabled.\n\n- suppressed - Appears in analytics but do not receive\n   messages. If a suppressed profile submits\n   an event the profile made active.\n */")
