/* <ALLOW_AUTO_DELETE DEPENDENCIES="Profile" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { ProfileGroupPlacement } from './ProfileGroupPlacement';
import { MessageTarget } from './MessageTarget';
import { NotificationDevice } from './NotificationDevice';
import { SubscriptionStatus } from './SubscriptionStatus';
import { EventRecord } from './EventRecord';
import { Worker } from './Worker';

export interface Profile
{
    id:number;
    accountId?:number;
    name?:string;
    firstName?:string;
    middleName?:string;
    lastName?:string;
    email?:string;
    website?:string;
    created?:number;
    lastActivity?:number;
    timezone?:string;
    phone?:string;
    country?:string;
    state?:string;
    city?:string;
    address?:string;
    address2?:string;
    postalCode?:string;
    birthDate?:number;
    identificationSource?:string;
    data?:Record<string,any>;
    /**
     * Usually the store the profile is associated with
     */
    primaryLocationId?:number;
    workers?:Worker[];
    events?:EventRecord[];
    status:SubscriptionStatus;
    notificationDevices?:NotificationDevice[];
    targetedMessages?:MessageTarget[];
    groupPlacements?:ProfileGroupPlacement[];
}
