/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroupPlacement" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ProfileGroupPlacement
{
    id:number;
    created:number;
    /**
     * The time when the profile placement was disabled.
     * For historical purposes profile placements are never
     * deleted they are only disabled.
     */
    disabledAt?:number;
    profileId:number;
    groupId:number;
}
