/* <ALLOW_AUTO_DELETE DEPENDENCIES="ProfileGroup" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Profile } from './Profile';
import type { ProfileGroupPlacement } from './ProfileGroupPlacement';
import type { Query } from './Query';
import type { ProfileGroupType } from './ProfileGroupType';

/**
 * Represents an audience or list of profiles.
 * Profile groups consists of profiles included by the
 * the groups query and by profiles that are directly
 * placed in the group via ProfileGroupPlacement records.
 */
export interface ProfileGroup
{
    id:number;
    name?:string;
    accountId?:number;
    created?:number;
    description?:string;
    lastUserCount?:number;
    type:ProfileGroupType;
    query?:Query;
    placedProfiles?:ProfileGroupPlacement[];
    identProfiles?:Profile[];
}
