/* <ALLOW_AUTO_DELETE DEPENDENCIES="QueryRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query } from './Query';

export interface QueryRecord
{
    id:string;
    name?:string;
    description?:string;
    ownerId?:number;
    accountId?:number;
    query:Query;
}
