/* <ALLOW_AUTO_DELETE DEPENDENCIES="Query" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__QueryScheme=z.object({
});
const __lazy__QueryScheme=z.object({
});
export const QueryScheme:(typeof __base__QueryScheme)=__base__QueryScheme.merge(__lazy__QueryScheme).passthrough() as any;
