/* <ALLOW_AUTO_DELETE DEPENDENCIES="QueryRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { QueryScheme } from './QueryScheme';

const __base__QueryRecordScheme=z.object({
    id:z.string().max(255),
    name:z.string().max(255).optional(),
    description:z.string().optional(),
    ownerId:z.number().int().optional(),
    accountId:z.number().int().optional(),
});
const __lazy__QueryRecordScheme=z.object({
    query:z.lazy(()=>QueryScheme),
});
export const QueryRecordScheme:(typeof __base__QueryRecordScheme)=__base__QueryRecordScheme.merge(__lazy__QueryRecordScheme) as any;
