/* <ALLOW_AUTO_DELETE DEPENDENCIES="Query" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Query as _import_ } from '@iyio/common';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Query extends _import_
{
}
