/* <ALLOW_AUTO_DELETE DEPENDENCIES="QueueSendMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SendMessageRequestScheme } from './SendMessageRequestScheme';

const __base__invokeQueueSendMessageFnFunctionArgsScheme=z.object({
});
const __lazy__invokeQueueSendMessageFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendMessageRequestScheme),
});
export const invokeQueueSendMessageFnFunctionArgsScheme:(typeof __base__invokeQueueSendMessageFnFunctionArgsScheme)=__base__invokeQueueSendMessageFnFunctionArgsScheme.merge(__lazy__invokeQueueSendMessageFnFunctionArgsScheme) as any;
