/* <ALLOW_AUTO_DELETE DEPENDENCIES="RecurringPrice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeIntervalTypeScheme } from './StripeIntervalTypeScheme';

const __base__RecurringPriceScheme=z.object({
    intervalCount:z.number().int(),
});
const __lazy__RecurringPriceScheme=z.object({
    interval:z.lazy(()=>StripeIntervalTypeScheme),
});
export const RecurringPriceScheme:(typeof __base__RecurringPriceScheme)=__base__RecurringPriceScheme.merge(__lazy__RecurringPriceScheme) as any;
