/* <ALLOW_AUTO_DELETE DEPENDENCIES="RecurringPrice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeIntervalType } from './StripeIntervalType';

export interface RecurringPrice
{
    intervalCount:number;
    interval:StripeIntervalType;
}
