/* <ALLOW_AUTO_DELETE DEPENDENCIES="Region" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { LocationScheme } from './LocationScheme';

const __base__RegionScheme=z.object({
    id:z.number().int(),
    accountId:z.number().int().optional(),
    created:z.number().optional(),
});
const __lazy__RegionScheme=z.object({
    locations:z.lazy(()=>LocationScheme).array().optional(),
});
export const RegionScheme:(typeof __base__RegionScheme)=__base__RegionScheme.merge(__lazy__RegionScheme) as any;
