/* <ALLOW_AUTO_DELETE DEPENDENCIES="Region" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { Location } from './Location';

export interface Region
{
    id:number;
    accountId?:number;
    locations?:Location[];
}
