/* <ALLOW_AUTO_DELETE DEPENDENCIES="RegisterPushDeviceRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__RegisterPushDeviceRequestScheme=z.object({
    profileUuid:z.string().max(255),
    pushEndpoint:z.string().max(255),
    pushSubscription:z.record(z.any()),
});
const __lazy__RegisterPushDeviceRequestScheme=z.object({
});
export const RegisterPushDeviceRequestScheme:(typeof __base__RegisterPushDeviceRequestScheme)=__base__RegisterPushDeviceRequestScheme.merge(__lazy__RegisterPushDeviceRequestScheme) as any;
