/* <ALLOW_AUTO_DELETE DEPENDENCIES="Region" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Location } from './Location';

export interface Region
{
    id:number;
    accountId?:number;
    created?:number;
    locations?:Location[];
}
