/* <ALLOW_AUTO_DELETE DEPENDENCIES="RegistrationVerificationRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__RegistrationVerificationRecordScheme=z.object({
    id:z.number().int(),
    created:z.number(),
    email:z.string().email(),
    code:z.string().max(255),
    revoked:z.boolean(),
    data:z.any().optional(),
    expires:z.number().optional(),
});
const __lazy__RegistrationVerificationRecordScheme=z.object({
});
export const RegistrationVerificationRecordScheme:(typeof __base__RegistrationVerificationRecordScheme)=__base__RegistrationVerificationRecordScheme.merge(__lazy__RegistrationVerificationRecordScheme) as any;
