/* <ALLOW_AUTO_DELETE DEPENDENCIES="RegistrationVerificationRecord" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface RegistrationVerificationRecord
{
    id:number;
    created:number;
    email:string;
    code:string;
    revoked:boolean;
    data?:any;
    expires?:number;
}
