/* <ALLOW_AUTO_DELETE DEPENDENCIES="RegisterPushDeviceRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface RegisterPushDeviceRequest
{
    profileUuid:string;
    pushEndpoint:string;
    pushSubscription:Record<string,any>;
}
