/* <ALLOW_AUTO_DELETE DEPENDENCIES="RenderFormOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { FormRecord } from './FormRecord';

export interface RenderFormOptions
{
    formId?:number;
    tag?:string;
    index?:number;
    profileUuid?:string;
    form?:FormRecord;
}
