/* <ALLOW_AUTO_DELETE DEPENDENCIES="RenderFormOptions" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { FormRecordScheme } from './FormRecordScheme';

const __base__RenderFormOptionsScheme=z.object({
    formId:z.number().int().optional(),
    tag:z.string().max(255).optional(),
    index:z.number().int().optional(),
    profileUuid:z.string().max(255).optional(),
});
const __lazy__RenderFormOptionsScheme=z.object({
    form:z.lazy(()=>FormRecordScheme).optional(),
});
export const RenderFormOptionsScheme:(typeof __base__RenderFormOptionsScheme)=__base__RenderFormOptionsScheme.merge(__lazy__RenderFormOptionsScheme) as any;
