/* <ALLOW_AUTO_DELETE DEPENDENCIES="RenderFormFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { RenderFormOptionsScheme } from './RenderFormOptionsScheme';

const __base__invokeRenderFormFnFunctionArgsScheme=z.object({
});
const __lazy__invokeRenderFormFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>RenderFormOptionsScheme),
});
export const invokeRenderFormFnFunctionArgsScheme:(typeof __base__invokeRenderFormFnFunctionArgsScheme)=__base__invokeRenderFormFnFunctionArgsScheme.merge(__lazy__invokeRenderFormFnFunctionArgsScheme) as any;
