/* <ALLOW_AUTO_DELETE DEPENDENCIES="RenderMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SendMessageRequestScheme } from './SendMessageRequestScheme';

const __base__invokeRenderMessageFnFunctionArgsScheme=z.object({
});
const __lazy__invokeRenderMessageFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendMessageRequestScheme),
});
export const invokeRenderMessageFnFunctionArgsScheme:(typeof __base__invokeRenderMessageFnFunctionArgsScheme)=__base__invokeRenderMessageFnFunctionArgsScheme.merge(__lazy__invokeRenderMessageFnFunctionArgsScheme) as any;
