/* <ALLOW_AUTO_DELETE DEPENDENCIES="RenderFormFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { RenderFormOptions } from './RenderFormOptions';

export interface invokeRenderFormFnFunctionArgs
{
    input:RenderFormOptions;
}
