/* <ALLOW_AUTO_DELETE DEPENDENCIES="ResourceAccessToken" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Stores calculated access information
 * for a single resource
 */
export interface ResourceAccessToken
{
    /**
     * Id of the resource the token
     * grants access to
     */
    resourceId:string;
    /**
     * The roles given by the token
     */
    roles:string[];
}
