/* <ALLOW_AUTO_DELETE DEPENDENCIES="ResourceAccessToken" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ResourceAccessTokenScheme=z.object({
    resourceId:z.string().max(255).describe("Id of the resource the token grants access to"),
    roles:z.string().max(255).array().describe("The roles given by the token"),
}).describe("Stores calculated access information for a single resource");
const __lazy__ResourceAccessTokenScheme=z.object({
});
export const ResourceAccessTokenScheme:(typeof __base__ResourceAccessTokenScheme)=__base__ResourceAccessTokenScheme.merge(__lazy__ResourceAccessTokenScheme) as any;
