/* <ALLOW_AUTO_DELETE DEPENDENCIES="SaveFormRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { FormRecordScheme } from './FormRecordScheme';

const __base__invokeSaveFormRecordFnFunctionArgsScheme=z.object({
}).describe("If the id of the FormRecord is 0 it is inserted as a new item");
const __lazy__invokeSaveFormRecordFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>FormRecordScheme),
});
export const invokeSaveFormRecordFnFunctionArgsScheme:(typeof __base__invokeSaveFormRecordFnFunctionArgsScheme)=__base__invokeSaveFormRecordFnFunctionArgsScheme.merge(__lazy__invokeSaveFormRecordFnFunctionArgsScheme) as any;
