/* <ALLOW_AUTO_DELETE DEPENDENCIES="SaveMessageTemplateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageTemplate } from './MessageTemplate';

/**
 * If the id of the MessageTemplate is
 * 0 it is inserted as a new item
 */
export interface invokeSaveMessageTemplateFnFunctionArgs
{
    input:MessageTemplate;
}
