/* <ALLOW_AUTO_DELETE DEPENDENCIES="SaveMessageTemplateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MessageTemplateScheme } from './MessageTemplateScheme';

const __base__invokeSaveMessageTemplateFnFunctionArgsScheme=z.object({
}).describe("If the id of the MessageTemplate is 0 it is inserted as a new item");
const __lazy__invokeSaveMessageTemplateFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>MessageTemplateScheme),
});
export const invokeSaveMessageTemplateFnFunctionArgsScheme:(typeof __base__invokeSaveMessageTemplateFnFunctionArgsScheme)=__base__invokeSaveMessageTemplateFnFunctionArgsScheme.merge(__lazy__invokeSaveMessageTemplateFnFunctionArgsScheme) as any;
