/* <ALLOW_AUTO_DELETE DEPENDENCIES="SaveFormRecordFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { FormRecord } from './FormRecord';

/**
 * If the id of the FormRecord is
 * 0 it is inserted as a new item
 */
export interface invokeSaveFormRecordFnFunctionArgs
{
    input:FormRecord;
}
