/* <ALLOW_AUTO_DELETE DEPENDENCIES="ScheduledAutomationCallbackFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ScheduledAutomationTriggerScheme } from './ScheduledAutomationTriggerScheme';

const __base__invokeScheduledAutomationCallbackFnFunctionArgsScheme=z.object({
});
const __lazy__invokeScheduledAutomationCallbackFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ScheduledAutomationTriggerScheme),
});
export const invokeScheduledAutomationCallbackFnFunctionArgsScheme:(typeof __base__invokeScheduledAutomationCallbackFnFunctionArgsScheme)=__base__invokeScheduledAutomationCallbackFnFunctionArgsScheme.merge(__lazy__invokeScheduledAutomationCallbackFnFunctionArgsScheme) as any;
