/* <ALLOW_AUTO_DELETE DEPENDENCIES="ScheduledAutomationCallbackFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ScheduledAutomationTrigger } from './ScheduledAutomationTrigger';

export interface invokeScheduledAutomationCallbackFnFunctionArgs
{
    input:ScheduledAutomationTrigger;
}
