/* <ALLOW_AUTO_DELETE DEPENDENCIES="ScheduledAutomationTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ScheduledAutomationTrigger
{
    version:number;
    /**
     * Id of an AutomationTriggerRecord to
     * load and trigger
     */
    recordId?:number;
    automationId?:number;
    nodeId?:string;
    traverserId?:string;
    fork?:boolean;
}
