/* <ALLOW_AUTO_DELETE DEPENDENCIES="ScheduledAutomationTrigger" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ScheduledAutomationTriggerScheme=z.object({
    version:z.number(),
    recordId:z.number().optional().describe("Id of an AutomationTriggerRecord to load and trigger"),
    automationId:z.number().optional(),
    nodeId:z.string().max(255).optional(),
    traverserId:z.string().max(255).optional(),
    fork:z.boolean().optional(),
});
const __lazy__ScheduledAutomationTriggerScheme=z.object({
});
export const ScheduledAutomationTriggerScheme:(typeof __base__ScheduledAutomationTriggerScheme)=__base__ScheduledAutomationTriggerScheme.merge(__lazy__ScheduledAutomationTriggerScheme) as any;
