/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendVerificationEmailFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface SendVerificationEmailFnInput
{
    email:string;
    data?:any;
}
