/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendVerificationEmailFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__SendVerificationEmailFnInputScheme=z.object({
    email:z.string().email(),
    data:z.any().optional(),
});
const __lazy__SendVerificationEmailFnInputScheme=z.object({
});
export const SendVerificationEmailFnInputScheme:(typeof __base__SendVerificationEmailFnInputScheme)=__base__SendVerificationEmailFnInputScheme.merge(__lazy__SendVerificationEmailFnInputScheme) as any;
