/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__SendContactRequestScheme=z.object({
    name:z.string().max(255).optional(),
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
    tag:z.string().max(255),
});
const __lazy__SendContactRequestScheme=z.object({
});
export const SendContactRequestScheme:(typeof __base__SendContactRequestScheme)=__base__SendContactRequestScheme.merge(__lazy__SendContactRequestScheme) as any;
