/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SendMessageRequestScheme } from './SendMessageRequestScheme';

const __base__invokeSendMessageFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSendMessageFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendMessageRequestScheme),
});
export const invokeSendMessageFnFunctionArgsScheme:(typeof __base__invokeSendMessageFnFunctionArgsScheme)=__base__invokeSendMessageFnFunctionArgsScheme.merge(__lazy__invokeSendMessageFnFunctionArgsScheme) as any;
