/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactResult" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface SendContactResult
{
    message:string;
}
