/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendTemplateMessageFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { SendTemplateMessageRequest } from './SendTemplateMessageRequest';

export interface invokeSendTemplateMessageFnFunctionArgs
{
    input:SendTemplateMessageRequest;
}
