/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MessageRenderTarget } from './MessageRenderTarget';
import type { MessageRecord } from './MessageRecord';
import type { CreateMessageRecordOptions } from './CreateMessageRecordOptions';

export interface SendMessageRequest
{
    messageId?:number;
    createMessage?:CreateMessageRecordOptions;
    messageRecord?:MessageRecord;
    renderTarget?:MessageRenderTarget;
}
