/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendDiscountFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { DiscountMessageRequest } from './DiscountMessageRequest';

/**
 * Sends a discount message to the target user
 */
export interface invokeSendDiscountFnFunctionArgs
{
    input:DiscountMessageRequest;
}
