/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendTemplateMessageRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { User } from './User';

export interface SendTemplateMessageRequest
{
    templateId:string;
    templateData:any;
    user:User;
}
