/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MessageRenderTargetScheme } from './MessageRenderTargetScheme';
import { MessageRecordScheme } from './MessageRecordScheme';
import { CreateMessageRecordOptionsScheme } from './CreateMessageRecordOptionsScheme';

const __base__SendMessageRequestScheme=z.object({
    messageId:z.number().int().optional(),
});
const __lazy__SendMessageRequestScheme=z.object({
    createMessage:z.lazy(()=>CreateMessageRecordOptionsScheme).optional(),
    messageRecord:z.lazy(()=>MessageRecordScheme).optional(),
    renderTarget:z.lazy(()=>MessageRenderTargetScheme).optional(),
});
export const SendMessageRequestScheme:(typeof __base__SendMessageRequestScheme)=__base__SendMessageRequestScheme.merge(__lazy__SendMessageRequestScheme) as any;
