/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface SendMessageRequest
{
    email:string;
}
