/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface SendContactRequest
{
    name?:string;
    email?:string;
    phone?:string;
    tag:string;
}
