/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactRequestFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SendContactRequestScheme } from './SendContactRequestScheme';

const __base__invokeSendContactRequestFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSendContactRequestFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendContactRequestScheme),
});
export const invokeSendContactRequestFnFunctionArgsScheme:(typeof __base__invokeSendContactRequestFnFunctionArgsScheme)=__base__invokeSendContactRequestFnFunctionArgsScheme.merge(__lazy__invokeSendContactRequestFnFunctionArgsScheme) as any;
