/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendTemplateMessageFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { SendTemplateMessageRequestScheme } from './SendTemplateMessageRequestScheme';

const __base__invokeSendTemplateMessageFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSendTemplateMessageFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendTemplateMessageRequestScheme),
});
export const invokeSendTemplateMessageFnFunctionArgsScheme:(typeof __base__invokeSendTemplateMessageFnFunctionArgsScheme)=__base__invokeSendTemplateMessageFnFunctionArgsScheme.merge(__lazy__invokeSendTemplateMessageFnFunctionArgsScheme) as any;
