/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendVerificationEmailFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { SendVerificationEmailFnInput } from './SendVerificationEmailFnInput';

export interface invokeSendVerificationEmailFnFunctionArgs
{
    input:SendVerificationEmailFnInput;
}
