/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { SendMessageRequest } from './SendMessageRequest';

export interface invokeSendMessageFnFunctionArgs
{
    input:SendMessageRequest;
}
