/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendMessageFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { SendMessageRequest } from './SendMessageRequest';

export interface invokeSendMessageFnFunctionArgs
{
    input:SendMessageRequest;
}
