/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactRequestFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { SendContactRequest } from './SendContactRequest';

export interface invokeSendContactRequestFnFunctionArgs
{
    input:SendContactRequest;
}
