/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactRequestFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { SendContactRequest } from './SendContactRequest';

export interface invokeSendContactRequestFnFunctionArgs
{
    input:SendContactRequest;
}
