/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendTemplateMessageRequest" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { UserScheme } from './UserScheme';

const __base__SendTemplateMessageRequestScheme=z.object({
    templateId:z.string().max(255),
    templateData:z.any(),
});
const __lazy__SendTemplateMessageRequestScheme=z.object({
    user:z.lazy(()=>UserScheme),
});
export const SendTemplateMessageRequestScheme:(typeof __base__SendTemplateMessageRequestScheme)=__base__SendTemplateMessageRequestScheme.merge(__lazy__SendTemplateMessageRequestScheme) as any;
