/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendVerificationEmailFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { SendVerificationEmailFnInputScheme } from './SendVerificationEmailFnInputScheme';

const __base__invokeSendVerificationEmailFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSendVerificationEmailFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>SendVerificationEmailFnInputScheme),
});
export const invokeSendVerificationEmailFnFunctionArgsScheme:(typeof __base__invokeSendVerificationEmailFnFunctionArgsScheme)=__base__invokeSendVerificationEmailFnFunctionArgsScheme.merge(__lazy__invokeSendVerificationEmailFnFunctionArgsScheme) as any;
