/* <ALLOW_AUTO_DELETE DEPENDENCIES="SendContactResult" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__SendContactResultScheme=z.object({
    message:z.string().max(255),
});
const __lazy__SendContactResultScheme=z.object({
});
export const SendContactResultScheme:(typeof __base__SendContactResultScheme)=__base__SendContactResultScheme.merge(__lazy__SendContactResultScheme) as any;
