/* <ALLOW_AUTO_DELETE DEPENDENCIES="Session" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { EventRecord } from './EventRecord';

/**
 * Represents a group of events group
 * by time
 */
export interface Session
{
    startTime:number;
    endTime:number;
    events?:EventRecord[];
}
