/* <ALLOW_AUTO_DELETE DEPENDENCIES="ShopifyUserStatus" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type ShopifyUserStatus=(
    "good"|
    "bad"|
    "ok"
);
