/* <ALLOW_AUTO_DELETE DEPENDENCIES="ShopifyUserStatus" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const ShopifyUserStatusScheme=z.enum([
    "good",
    "bad",
    "ok",
]);
