/* <ALLOW_AUTO_DELETE DEPENDENCIES="SignInInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface SignInInfo
{
    username:string;
    password:string;
}
