/* <ALLOW_AUTO_DELETE DEPENDENCIES="SignInInfo" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__SignInInfoScheme=z.object({
    username:z.string().max(255),
    password:z.string().max(255),
});
const __lazy__SignInInfoScheme=z.object({
});
export const SignInInfoScheme:(typeof __base__SignInInfoScheme)=__base__SignInInfoScheme.merge(__lazy__SignInInfoScheme) as any;
