/* <ALLOW_AUTO_DELETE DEPENDENCIES="SocialType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const SocialTypeScheme=z.enum([
    "linkedin",
    "x",
    "twitter",
    "youtube",
    "facebook",
    "instagram",
    "tiktok",
    "discord",
    "reddit",
    "twitch",
    "pinterest",
    "tumblr",
]);
