/* <ALLOW_AUTO_DELETE DEPENDENCIES="SocialType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "linkedin",
    "x",
    "twitter",
    "youtube",
    "facebook",
    "instagram",
    "tiktok",
    "discord",
    "reddit",
    "twitch",
    "pinterest",
    "tumblr"
] as const;
Object.freeze(unionAry);

export type SocialType=typeof unionAry[number];

export const allSocialTypeAry:SocialType[]=unionAry as any;
