/* <ALLOW_AUTO_DELETE DEPENDENCIES="SocialItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { SocialType } from './SocialType';

export interface SocialItem
{
    link:string;
    disabled?:boolean;
    type:SocialType;
}
