/* <ALLOW_AUTO_DELETE DEPENDENCIES="SqlSelectRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__SqlSelectRequestScheme=z.object({
    sql:z.string(),
    keepNulls:z.boolean().optional(),
});
const __lazy__SqlSelectRequestScheme=z.object({
});
export const SqlSelectRequestScheme:(typeof __base__SqlSelectRequestScheme)=__base__SqlSelectRequestScheme.merge(__lazy__SqlSelectRequestScheme) as any;
