/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionUpdateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeSubscriptionUpdateFnIO } from './StripeSubscriptionUpdateFnIO';

export interface invokeStripeSubscriptionUpdateFnFunctionArgs
{
    input:StripeSubscriptionUpdateFnIO;
}
