/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionUpdateFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeSubscriptionUpdateFnIOScheme } from './StripeSubscriptionUpdateFnIOScheme';

const __base__invokeStripeSubscriptionUpdateFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeSubscriptionUpdateFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>StripeSubscriptionUpdateFnIOScheme),
});
export const invokeStripeSubscriptionUpdateFnFunctionArgsScheme:(typeof __base__invokeStripeSubscriptionUpdateFnFunctionArgsScheme)=__base__invokeStripeSubscriptionUpdateFnFunctionArgsScheme.merge(__lazy__invokeStripeSubscriptionUpdateFnFunctionArgsScheme) as any;
