/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCustomerPortalFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeStripeCustomerPortalFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeCustomerPortalFnFunctionArgsScheme=z.object({
});
export const invokeStripeCustomerPortalFnFunctionArgsScheme:(typeof __base__invokeStripeCustomerPortalFnFunctionArgsScheme)=__base__invokeStripeCustomerPortalFnFunctionArgsScheme.merge(__lazy__invokeStripeCustomerPortalFnFunctionArgsScheme) as any;
