/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeCheckoutSessionFnInputScheme } from './StripeCheckoutSessionFnInputScheme';

const __base__invokeStripeCheckoutSessionFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeCheckoutSessionFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>StripeCheckoutSessionFnInputScheme),
});
export const invokeStripeCheckoutSessionFnFunctionArgsScheme:(typeof __base__invokeStripeCheckoutSessionFnFunctionArgsScheme)=__base__invokeStripeCheckoutSessionFnFunctionArgsScheme.merge(__lazy__invokeStripeCheckoutSessionFnFunctionArgsScheme) as any;
