/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCategorizedProducts" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeSubscriptionItemScheme } from './StripeSubscriptionItemScheme';

const __base__StripeCategorizedProductsScheme=z.object({
});
const __lazy__StripeCategorizedProductsScheme=z.object({
    profiles:z.lazy(()=>StripeSubscriptionItemScheme),
    sms:z.lazy(()=>StripeSubscriptionItemScheme).optional(),
    addOns:z.lazy(()=>StripeSubscriptionItemScheme).array().optional(),
});
export const StripeCategorizedProductsScheme:(typeof __base__StripeCategorizedProductsScheme)=__base__StripeCategorizedProductsScheme.merge(__lazy__StripeCategorizedProductsScheme) as any;
