/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeIntervalType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const StripeIntervalTypeScheme=z.enum([
    "day",
    "week",
    "month",
    "year",
]);
