/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeProduct" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { MarketingFeatureScheme } from './MarketingFeatureScheme';
import { PriceScheme } from './PriceScheme';

const __base__StripeProductScheme=z.object({
    id:z.string().max(255).describe("Stripe product id"),
    description:z.string().optional(),
    name:z.string().max(255),
    quantity:z.number().int(),
});
const __lazy__StripeProductScheme=z.object({
    defaultPrice:z.lazy(()=>PriceScheme),
    marketingFeatures:z.lazy(()=>MarketingFeatureScheme).array().optional(),
});
export const StripeProductScheme:(typeof __base__StripeProductScheme)=__base__StripeProductScheme.merge(__lazy__StripeProductScheme) as any;
