/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripePriceType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const StripePriceTypeScheme=z.enum([
    "oneTime",
    "recurring",
]);
