/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeCheckoutFnInput } from './StripeCheckoutFnInput';

export interface invokeStripeCheckoutFnFunctionArgs
{
    input:StripeCheckoutFnInput;
}
