/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionReturnFnOutput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeProduct } from './StripeProduct';

export interface StripeCheckoutSessionReturnFnOutput
{
    billingDate?:number;
    subtotal?:number;
    tax?:number;
    total?:number;
    monthlyDiscount?:number;
    oneTimeDiscount?:number;
    products?:StripeProduct[];
}
