/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeProduct" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { MarketingFeature } from './MarketingFeature';
import type { Price } from './Price';

export interface StripeProduct
{
    /**
     * Stripe product id
     */
    id:string;
    description?:string;
    name:string;
    quantity:number;
    defaultPrice:Price;
    marketingFeatures?:MarketingFeature[];
}
