/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionReturnFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeCheckoutSessionReturnFnInputScheme } from './StripeCheckoutSessionReturnFnInputScheme';

const __base__invokeStripeCheckoutSessionReturnFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeCheckoutSessionReturnFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>StripeCheckoutSessionReturnFnInputScheme),
});
export const invokeStripeCheckoutSessionReturnFnFunctionArgsScheme:(typeof __base__invokeStripeCheckoutSessionReturnFnFunctionArgsScheme)=__base__invokeStripeCheckoutSessionReturnFnFunctionArgsScheme.merge(__lazy__invokeStripeCheckoutSessionReturnFnFunctionArgsScheme) as any;
