/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionReturnFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface StripeCheckoutSessionReturnFnInput
{
    sessionId:string;
    id:number;
}
