/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeCheckoutFnInputScheme } from './StripeCheckoutFnInputScheme';

const __base__invokeStripeCheckoutFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeCheckoutFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>StripeCheckoutFnInputScheme),
});
export const invokeStripeCheckoutFnFunctionArgsScheme:(typeof __base__invokeStripeCheckoutFnFunctionArgsScheme)=__base__invokeStripeCheckoutFnFunctionArgsScheme.merge(__lazy__invokeStripeCheckoutFnFunctionArgsScheme) as any;
