/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeCheckoutSessionFnInput } from './StripeCheckoutSessionFnInput';

export interface invokeStripeCheckoutSessionFnFunctionArgs
{
    input:StripeCheckoutSessionFnInput;
}
