/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSecret" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeSecretScheme=z.object({
    stripeSecretKey:z.string().max(255),
});
const __lazy__StripeSecretScheme=z.object({
});
export const StripeSecretScheme:(typeof __base__StripeSecretScheme)=__base__StripeSecretScheme.merge(__lazy__StripeSecretScheme) as any;
