/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeProductScheme } from './StripeProductScheme';

const __base__StripeSubscriptionItemScheme=z.object({
    itemId:z.string().max(255).optional().describe("Stripe subscription item id"),
});
const __lazy__StripeSubscriptionItemScheme=z.object({
    product:z.lazy(()=>StripeProductScheme),
});
export const StripeSubscriptionItemScheme:(typeof __base__StripeSubscriptionItemScheme)=__base__StripeSubscriptionItemScheme.merge(__lazy__StripeSubscriptionItemScheme) as any;
