/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionProduct" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeCheckoutSessionProductScheme=z.object({
    price:z.string().max(255),
    product:z.string().max(255),
    quantity:z.number().int(),
});
const __lazy__StripeCheckoutSessionProductScheme=z.object({
});
export const StripeCheckoutSessionProductScheme:(typeof __base__StripeCheckoutSessionProductScheme)=__base__StripeCheckoutSessionProductScheme.merge(__lazy__StripeCheckoutSessionProductScheme) as any;
