/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeInvoice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeSubscriptionItemScheme } from './StripeSubscriptionItemScheme';

const __base__StripeInvoiceScheme=z.object({
    total:z.number(),
    subtotal:z.number(),
    tax:z.number(),
    discounts:z.number().array(),
});
const __lazy__StripeInvoiceScheme=z.object({
    items:z.lazy(()=>StripeSubscriptionItemScheme).array(),
});
export const StripeInvoiceScheme:(typeof __base__StripeInvoiceScheme)=__base__StripeInvoiceScheme.merge(__lazy__StripeInvoiceScheme) as any;
