/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionFnOutput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeCheckoutSessionFnOutputScheme=z.object({
    clientSecret:z.string(),
});
const __lazy__StripeCheckoutSessionFnOutputScheme=z.object({
});
export const StripeCheckoutSessionFnOutputScheme:(typeof __base__StripeCheckoutSessionFnOutputScheme)=__base__StripeCheckoutSessionFnOutputScheme.merge(__lazy__StripeCheckoutSessionFnOutputScheme) as any;
