/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCategorizedProducts" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeSubscriptionItem } from './StripeSubscriptionItem';

export interface StripeCategorizedProducts
{
    profiles:StripeSubscriptionItem;
    sms?:StripeSubscriptionItem;
    addOns?:StripeSubscriptionItem[];
}
