/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripePriceType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "oneTime",
    "recurring"
] as const;
Object.freeze(unionAry);

export type StripePriceType=typeof unionAry[number];

export const allStripePriceTypeAry:StripePriceType[]=unionAry as any;
