/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCurrentSubscriptionFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeStripeCurrentSubscriptionFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeCurrentSubscriptionFnFunctionArgsScheme=z.object({
});
export const invokeStripeCurrentSubscriptionFnFunctionArgsScheme:(typeof __base__invokeStripeCurrentSubscriptionFnFunctionArgsScheme)=__base__invokeStripeCurrentSubscriptionFnFunctionArgsScheme.merge(__lazy__invokeStripeCurrentSubscriptionFnFunctionArgsScheme) as any;
