/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeCheckoutSessionProductScheme } from './StripeCheckoutSessionProductScheme';

const __base__StripeCheckoutSessionFnInputScheme=z.object({
    id:z.number().int(),
    autoUpgrade:z.boolean().optional(),
});
const __lazy__StripeCheckoutSessionFnInputScheme=z.object({
    products:z.lazy(()=>StripeCheckoutSessionProductScheme).array(),
});
export const StripeCheckoutSessionFnInputScheme:(typeof __base__StripeCheckoutSessionFnInputScheme)=__base__StripeCheckoutSessionFnInputScheme.merge(__lazy__StripeCheckoutSessionFnInputScheme) as any;
