/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionReturnFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeCheckoutSessionReturnFnInputScheme=z.object({
    sessionId:z.string().max(255),
    id:z.number().int(),
});
const __lazy__StripeCheckoutSessionReturnFnInputScheme=z.object({
});
export const StripeCheckoutSessionReturnFnInputScheme:(typeof __base__StripeCheckoutSessionReturnFnInputScheme)=__base__StripeCheckoutSessionReturnFnInputScheme.merge(__lazy__StripeCheckoutSessionReturnFnInputScheme) as any;
