/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeUpcomingInvoiceFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeStripeUpcomingInvoiceFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeUpcomingInvoiceFnFunctionArgsScheme=z.object({
});
export const invokeStripeUpcomingInvoiceFnFunctionArgsScheme:(typeof __base__invokeStripeUpcomingInvoiceFnFunctionArgsScheme)=__base__invokeStripeUpcomingInvoiceFnFunctionArgsScheme.merge(__lazy__invokeStripeUpcomingInvoiceFnFunctionArgsScheme) as any;
