/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeCheckoutFnInputScheme=z.object({
    amount:z.number(),
});
const __lazy__StripeCheckoutFnInputScheme=z.object({
});
export const StripeCheckoutFnInputScheme:(typeof __base__StripeCheckoutFnInputScheme)=__base__StripeCheckoutFnInputScheme.merge(__lazy__StripeCheckoutFnInputScheme) as any;
