/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionReturnFnOutput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeProductScheme } from './StripeProductScheme';

const __base__StripeCheckoutSessionReturnFnOutputScheme=z.object({
    billingDate:z.number().optional(),
    subtotal:z.number().optional(),
    tax:z.number().optional(),
    total:z.number().optional(),
    monthlyDiscount:z.number().optional(),
    oneTimeDiscount:z.number().optional(),
});
const __lazy__StripeCheckoutSessionReturnFnOutputScheme=z.object({
    products:z.lazy(()=>StripeProductScheme).array().optional(),
});
export const StripeCheckoutSessionReturnFnOutputScheme:(typeof __base__StripeCheckoutSessionReturnFnOutputScheme)=__base__StripeCheckoutSessionReturnFnOutputScheme.merge(__lazy__StripeCheckoutSessionReturnFnOutputScheme) as any;
