/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutSessionFnInput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeCheckoutSessionProduct } from './StripeCheckoutSessionProduct';

export interface StripeCheckoutSessionFnInput
{
    id:number;
    autoUpgrade?:boolean;
    products:StripeCheckoutSessionProduct[];
}
