/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeInvoice" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeSubscriptionItem } from './StripeSubscriptionItem';

export interface StripeInvoice
{
    total:number;
    subtotal:number;
    tax:number;
    discounts:number[];
    items:StripeSubscriptionItem[];
}
