/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCheckoutFnOutput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__StripeCheckoutFnOutputScheme=z.object({
    clientSecret:z.string(),
});
const __lazy__StripeCheckoutFnOutputScheme=z.object({
});
export const StripeCheckoutFnOutputScheme:(typeof __base__StripeCheckoutFnOutputScheme)=__base__StripeCheckoutFnOutputScheme.merge(__lazy__StripeCheckoutFnOutputScheme) as any;
