/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeProduct } from './StripeProduct';

export interface StripeSubscriptionItem
{
    /**
     * Stripe subscription item id
     */
    itemId?:string;
    product:StripeProduct;
}
