/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionUpdateFnIO" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StripeCategorizedProducts } from './StripeCategorizedProducts';

export interface StripeSubscriptionUpdateFnIO
{
    oldPlan:StripeCategorizedProducts;
    newPlan:StripeCategorizedProducts;
}
