/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeCustomerCreateFnOutput" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountRegistrationScheme } from './AccountRegistrationScheme';

const __base__StripeCustomerCreateFnOutputScheme=z.object({
    addressValid:z.boolean(),
});
const __lazy__StripeCustomerCreateFnOutputScheme=z.object({
    account:z.lazy(()=>AccountRegistrationScheme).optional(),
});
export const StripeCustomerCreateFnOutputScheme:(typeof __base__StripeCustomerCreateFnOutputScheme)=__base__StripeCustomerCreateFnOutputScheme.merge(__lazy__StripeCustomerCreateFnOutputScheme) as any;
