/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeProductsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeStripeProductsFnFunctionArgsScheme=z.object({
});
const __lazy__invokeStripeProductsFnFunctionArgsScheme=z.object({
});
export const invokeStripeProductsFnFunctionArgsScheme:(typeof __base__invokeStripeProductsFnFunctionArgsScheme)=__base__invokeStripeProductsFnFunctionArgsScheme.merge(__lazy__invokeStripeProductsFnFunctionArgsScheme) as any;
