/* <ALLOW_AUTO_DELETE DEPENDENCIES="StripeSubscriptionUpdateFnIO" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StripeCategorizedProductsScheme } from './StripeCategorizedProductsScheme';

const __base__StripeSubscriptionUpdateFnIOScheme=z.object({
});
const __lazy__StripeSubscriptionUpdateFnIOScheme=z.object({
    oldPlan:z.lazy(()=>StripeCategorizedProductsScheme),
    newPlan:z.lazy(()=>StripeCategorizedProductsScheme),
});
export const StripeSubscriptionUpdateFnIOScheme:(typeof __base__StripeSubscriptionUpdateFnIOScheme)=__base__StripeSubscriptionUpdateFnIOScheme.merge(__lazy__StripeSubscriptionUpdateFnIOScheme) as any;
