/* <ALLOW_AUTO_DELETE DEPENDENCIES="StrMatchType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "equals",
    "contains",
    "startsWith",
    "endsWith",
    "starMatch",
    "regexMatch"
] as const;
Object.freeze(unionAry);

export type StrMatchType=typeof unionAry[number];

export const allStrMatchTypeAry:StrMatchType[]=unionAry as any;
