/* <ALLOW_AUTO_DELETE DEPENDENCIES="StrMatchType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const StrMatchTypeScheme=z.enum([
    "equals",
    "contains",
    "startsWith",
    "endsWith",
    "starMatch",
    "regexMatch",
]);
