/* <ALLOW_AUTO_DELETE DEPENDENCIES="StrMatch" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { StrMatchType } from './StrMatchType';

export interface StrMatch
{
    key?:string;
    value:string;
    matchType:StrMatchType;
}
