/* <ALLOW_AUTO_DELETE DEPENDENCIES="StrMatch" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { StrMatchTypeScheme } from './StrMatchTypeScheme';

const __base__StrMatchScheme=z.object({
    key:z.string().optional(),
    value:z.string(),
});
const __lazy__StrMatchScheme=z.object({
    matchType:z.lazy(()=>StrMatchTypeScheme),
});
export const StrMatchScheme:(typeof __base__StrMatchScheme)=__base__StrMatchScheme.merge(__lazy__StrMatchScheme) as any;
