/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitProfileDataRequestFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeSubmitProfileDataRequestFnFunctionArgsScheme=z.object({
    input:z.any(),
});
const __lazy__invokeSubmitProfileDataRequestFnFunctionArgsScheme=z.object({
});
export const invokeSubmitProfileDataRequestFnFunctionArgsScheme:(typeof __base__invokeSubmitProfileDataRequestFnFunctionArgsScheme)=__base__invokeSubmitProfileDataRequestFnFunctionArgsScheme.merge(__lazy__invokeSubmitProfileDataRequestFnFunctionArgsScheme) as any;
