/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitEventsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeSubmitEventsFnFunctionArgsScheme=z.object({
    input:z.any().array(),
});
const __lazy__invokeSubmitEventsFnFunctionArgsScheme=z.object({
});
export const invokeSubmitEventsFnFunctionArgsScheme:(typeof __base__invokeSubmitEventsFnFunctionArgsScheme)=__base__invokeSubmitEventsFnFunctionArgsScheme.merge(__lazy__invokeSubmitEventsFnFunctionArgsScheme) as any;
