/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitEventsFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeSubmitEventsFnFunctionArgs
{
    input:any[];
}
