/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitProfileDataDeleteFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeSubmitProfileDataDeleteFnFunctionArgsScheme=z.object({
    input:z.any(),
});
const __lazy__invokeSubmitProfileDataDeleteFnFunctionArgsScheme=z.object({
});
export const invokeSubmitProfileDataDeleteFnFunctionArgsScheme:(typeof __base__invokeSubmitProfileDataDeleteFnFunctionArgsScheme)=__base__invokeSubmitProfileDataDeleteFnFunctionArgsScheme.merge(__lazy__invokeSubmitProfileDataDeleteFnFunctionArgsScheme) as any;
