/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitEventsFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { EventSubmissionScheme } from './EventSubmissionScheme';

const __base__invokeSubmitEventsFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSubmitEventsFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>EventSubmissionScheme),
});
export const invokeSubmitEventsFnFunctionArgsScheme:(typeof __base__invokeSubmitEventsFnFunctionArgsScheme)=__base__invokeSubmitEventsFnFunctionArgsScheme.merge(__lazy__invokeSubmitEventsFnFunctionArgsScheme) as any;
