/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitItemFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeSubmitItemFnFunctionArgs
{
    input:any;
}
