/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitLocationDataDeleteFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface invokeSubmitLocationDataDeleteFnFunctionArgs
{
    input:any;
}
