/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitLocationDataDeleteFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeSubmitLocationDataDeleteFnFunctionArgsScheme=z.object({
    input:z.any(),
});
const __lazy__invokeSubmitLocationDataDeleteFnFunctionArgsScheme=z.object({
});
export const invokeSubmitLocationDataDeleteFnFunctionArgsScheme:(typeof __base__invokeSubmitLocationDataDeleteFnFunctionArgsScheme)=__base__invokeSubmitLocationDataDeleteFnFunctionArgsScheme.merge(__lazy__invokeSubmitLocationDataDeleteFnFunctionArgsScheme) as any;
