/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitEventsFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { EventSubmission } from './EventSubmission';

export interface invokeSubmitEventsFnFunctionArgs
{
    input:EventSubmission;
}
