/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitAccountRegistrationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountRegistrationScheme } from './AccountRegistrationScheme';

const __base__invokeSubmitAccountRegistrationFnFunctionArgsScheme=z.object({
});
const __lazy__invokeSubmitAccountRegistrationFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>AccountRegistrationScheme),
});
export const invokeSubmitAccountRegistrationFnFunctionArgsScheme:(typeof __base__invokeSubmitAccountRegistrationFnFunctionArgsScheme)=__base__invokeSubmitAccountRegistrationFnFunctionArgsScheme.merge(__lazy__invokeSubmitAccountRegistrationFnFunctionArgsScheme) as any;
