/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitProfileDataRequestFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface invokeSubmitProfileDataRequestFnFunctionArgs
{
    input:any;
}
