/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitItemFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface invokeSubmitItemFnFunctionArgs
{
    input:any;
}
