/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitProfileDataDeleteFn" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface invokeSubmitProfileDataDeleteFnFunctionArgs
{
    input:any;
}
