/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubmitAccountRegistrationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountRegistration } from './AccountRegistration';

export interface invokeSubmitAccountRegistrationFnFunctionArgs
{
    input:AccountRegistration;
}
