/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubscriptionStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "neverSubscribed",
    "subscribed",
    "unsubscribed"
] as const;
Object.freeze(unionAry);

export type SubscriptionStatus=typeof unionAry[number];

export const allSubscriptionStatusAry:SubscriptionStatus[]=unionAry as any;
