/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubscriptionStatus" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type SubscriptionStatus=(
    "unverified"|
    "subscribed"|
    "unsubscribed"
);
