/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubscriptionStatus" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const SubscriptionStatusScheme=z.enum([
    "neverSubscribed",
    "subscribed",
    "unsubscribed",
]);
