/* <ALLOW_AUTO_DELETE DEPENDENCIES="SubscriptionStatus" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const SubscriptionStatusScheme=z.enum([
    "unverified",
    "subscribed",
    "unsubscribed",
]);
