/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "text",
    "image",
    "button",
    "header",
    "hr",
    "socials",
    "product",
    "table",
    "link",
    "textInput"
] as const;
Object.freeze(unionAry);

export type TemplateItemType=typeof unionAry[number];

export const allTemplateItemTypeAry:TemplateItemType[]=unionAry as any;
