/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateSection" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { TemplateVisibility } from './TemplateVisibility';
import type { TemplateBlock } from './TemplateBlock';

export interface TemplateSection
{
    /**
     * Column widths percentages as 0 to
     * 1 values
     */
    cols?:number[];
    wrap?:boolean;
    /**
     * Id of the MessageTemplate that the section
     * was sourced from
     */
    sourceTemplateId?:number;
    tid?:string;
    marginTop?:string;
    marginBottom?:string;
    marginLeft?:string;
    marginRight?:string;
    paddingTop?:string;
    paddingBottom?:string;
    paddingLeft?:string;
    paddingRight?:string;
    foregroundColor?:string;
    bgColor?:string;
    fontSize?:string;
    fontFamily?:string;
    lineHeight?:string;
    borderRadius?:string;
    primaryColor?:string;
    borderLeftWidth?:string;
    borderLeftColor?:string;
    borderLeftStyle?:string;
    borderRightWidth?:string;
    borderRightColor?:string;
    borderRightStyle?:string;
    borderTopWidth?:string;
    borderTopColor?:string;
    borderTopStyle?:string;
    borderBottomWidth?:string;
    borderBottomColor?:string;
    borderBottomStyle?:string;
    className?:string;
    metadata?:Record<string,any>;
    blocks:TemplateBlock[];
    visibility?:TemplateVisibility;
}
