/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateVisibility" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const TemplateVisibilityScheme=z.enum([
    "all",
    "desktop",
    "mobile",
]);
