/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateAlignment" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "left",
    "center",
    "right"
] as const;
Object.freeze(unionAry);

export type TemplateAlignment=typeof unionAry[number];

export const allTemplateAlignmentAry:TemplateAlignment[]=unionAry as any;
