/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateObjType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const TemplateObjTypeScheme=z.enum([
    "model",
    "container",
    "section",
    "block",
    "item",
]);
