/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateAlignment" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const TemplateAlignmentScheme=z.enum([
    "left",
    "center",
    "right",
]);
