/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateBorderStyle" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const TemplateBorderStyleScheme=z.enum([
    "solid",
    "dashed",
    "dotted",
    "double",
]);
