/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateVisibility" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "all",
    "desktop",
    "mobile"
] as const;
Object.freeze(unionAry);

export type TemplateVisibility=typeof unionAry[number];

export const allTemplateVisibilityAry:TemplateVisibility[]=unionAry as any;
