/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemOption" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface TemplateItemOption
{
    name:string;
    value:any;
}
