/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateBorderStyle" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "solid",
    "dashed",
    "dotted",
    "double"
] as const;
Object.freeze(unionAry);

export type TemplateBorderStyle=typeof unionAry[number];

export const allTemplateBorderStyleAry:TemplateBorderStyle[]=unionAry as any;
