/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateContainer" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { TemplateVisibilityScheme } from './TemplateVisibilityScheme';
import { TemplateAlignmentScheme } from './TemplateAlignmentScheme';
import { TemplateSectionScheme } from './TemplateSectionScheme';

const __base__TemplateContainerScheme=z.object({
    width:z.string().max(255).optional(),
    tid:z.string().max(255).optional(),
    marginTop:z.string().max(255).optional(),
    marginBottom:z.string().max(255).optional(),
    marginLeft:z.string().max(255).optional(),
    marginRight:z.string().max(255).optional(),
    paddingTop:z.string().max(255).optional(),
    paddingBottom:z.string().max(255).optional(),
    paddingLeft:z.string().max(255).optional(),
    paddingRight:z.string().max(255).optional(),
    foregroundColor:z.string().max(255).optional(),
    bgColor:z.string().max(255).optional(),
    fontSize:z.string().max(255).optional(),
    fontFamily:z.string().max(255).optional(),
    lineHeight:z.string().max(255).optional(),
    borderRadius:z.string().max(255).optional(),
    primaryColor:z.string().max(255).optional(),
    borderLeftWidth:z.string().max(255).optional(),
    borderLeftColor:z.string().max(255).optional(),
    borderLeftStyle:z.string().max(255).optional(),
    borderRightWidth:z.string().max(255).optional(),
    borderRightColor:z.string().max(255).optional(),
    borderRightStyle:z.string().max(255).optional(),
    borderTopWidth:z.string().max(255).optional(),
    borderTopColor:z.string().max(255).optional(),
    borderTopStyle:z.string().max(255).optional(),
    borderBottomWidth:z.string().max(255).optional(),
    borderBottomColor:z.string().max(255).optional(),
    borderBottomStyle:z.string().max(255).optional(),
    className:z.string().max(255).optional(),
    metadata:z.record(z.any()).optional(),
});
const __lazy__TemplateContainerScheme=z.object({
    sections:z.lazy(()=>TemplateSectionScheme).array(),
    alignment:z.lazy(()=>TemplateAlignmentScheme).optional(),
    visibility:z.lazy(()=>TemplateVisibilityScheme).optional(),
});
export const TemplateContainerScheme:(typeof __base__TemplateContainerScheme)=__base__TemplateContainerScheme.merge(__lazy__TemplateContainerScheme) as any;
