/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemOption" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__TemplateItemOptionScheme=z.object({
    name:z.string().max(255),
    value:z.any(),
});
const __lazy__TemplateItemOptionScheme=z.object({
});
export const TemplateItemOptionScheme:(typeof __base__TemplateItemOptionScheme)=__base__TemplateItemOptionScheme.merge(__lazy__TemplateItemOptionScheme) as any;
