/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemCell" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface TemplateItemCell
{
    col:number;
    row:number;
    text?:string;
    markdown?:string;
    foregroundColor?:string;
    fontSize?:string;
}
