/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemCell" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__TemplateItemCellScheme=z.object({
    col:z.number().int(),
    row:z.number().int(),
    text:z.string().optional(),
    markdown:z.string().optional(),
    foregroundColor:z.string().max(255).optional(),
    fontSize:z.string().max(255).optional(),
});
const __lazy__TemplateItemCellScheme=z.object({
});
export const TemplateItemCellScheme:(typeof __base__TemplateItemCellScheme)=__base__TemplateItemCellScheme.merge(__lazy__TemplateItemCellScheme) as any;
