/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItemType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const TemplateItemTypeScheme=z.enum([
    "text",
    "image",
    "button",
    "header",
    "hr",
    "socials",
    "product",
    "table",
    "link",
    "textInput",
]);
