/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateItem" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { TemplateVisibility } from './TemplateVisibility';
import type { TemplateItemOption } from './TemplateItemOption';
import type { TemplateItemCell } from './TemplateItemCell';
import type { InputType } from './InputType';
import type { TemplateAlignment } from './TemplateAlignment';
import type { SocialItem } from './SocialItem';
import type { TemplateItemType } from './TemplateItemType';

export interface TemplateItem
{
    name?:string;
    text?:string;
    markdown?:string;
    url?:string;
    linkUrl?:string;
    /**
     * Name of profile property to update
     * when used within a form
     */
    profileProp?:string;
    /**
     * Action to commit when clicked
     */
    action?:string;
    actionSource?:string;
    fileId?:number;
    description?:string;
    headerLevel?:number;
    maxWidth?:string;
    /**
     * Used by textInput
     */
    maxLength?:number;
    height?:string;
    size?:number;
    placeholder?:string;
    required?:boolean;
    /**
     * Used by textInput to define the
     * required value format
     */
    formatRegex?:string;
    inputTrueValue?:any;
    inputFalseValue?:any;
    enabled?:boolean;
    rows?:number;
    cols?:number;
    innerHBorderWidth?:string;
    innerHBorderColor?:string;
    innerHBorderStyle?:string;
    innerVBorderWidth?:string;
    innerVBorderColor?:string;
    innerVBorderStyle?:string;
    altBgColor?:string;
    altBg?:boolean;
    labelFontSize?:string;
    labelColor?:string;
    labelMargin?:string;
    utmSource?:string;
    utmMedium?:string;
    utmCampaign?:string;
    utmContent?:string;
    defaultValue?:string;
    tid?:string;
    marginTop?:string;
    marginBottom?:string;
    marginLeft?:string;
    marginRight?:string;
    paddingTop?:string;
    paddingBottom?:string;
    paddingLeft?:string;
    paddingRight?:string;
    foregroundColor?:string;
    bgColor?:string;
    fontSize?:string;
    fontFamily?:string;
    lineHeight?:string;
    borderRadius?:string;
    primaryColor?:string;
    borderLeftWidth?:string;
    borderLeftColor?:string;
    borderLeftStyle?:string;
    borderRightWidth?:string;
    borderRightColor?:string;
    borderRightStyle?:string;
    borderTopWidth?:string;
    borderTopColor?:string;
    borderTopStyle?:string;
    borderBottomWidth?:string;
    borderBottomColor?:string;
    borderBottomStyle?:string;
    className?:string;
    metadata?:Record<string,any>;
    type:TemplateItemType;
    socials?:SocialItem[];
    alignment?:TemplateAlignment;
    inputType?:InputType;
    cells?:TemplateItemCell[];
    options?:TemplateItemOption[];
    visibility?:TemplateVisibility;
}
