/* <ALLOW_AUTO_DELETE DEPENDENCIES="TemplateObjType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "model",
    "container",
    "section",
    "block",
    "item"
] as const;
Object.freeze(unionAry);

export type TemplateObjType=typeof unionAry[number];

export const allTemplateObjTypeAry:TemplateObjType[]=unionAry as any;
