/* <ALLOW_AUTO_DELETE DEPENDENCIES="ThemeData" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface ThemeData
{
    backgroundColor?:string;
    foregroundColor?:string;
    primaryColor?:string;
}
