/* <ALLOW_AUTO_DELETE DEPENDENCIES="ThemeData" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__ThemeDataScheme=z.object({
    backgroundColor:z.string().max(255).optional(),
    foregroundColor:z.string().max(255).optional(),
    primaryColor:z.string().max(255).optional(),
});
const __lazy__ThemeDataScheme=z.object({
});
export const ThemeDataScheme:(typeof __base__ThemeDataScheme)=__base__ThemeDataScheme.merge(__lazy__ThemeDataScheme) as any;
