/* <ALLOW_AUTO_DELETE DEPENDENCIES="TmpChangeAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeTmpChangeAccountFnFunctionArgs
{
    /**
     * Id of the account to join
     */
    input:number;
}
