/* <ALLOW_AUTO_DELETE DEPENDENCIES="TmpChangeAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeTmpChangeAccountFnFunctionArgsScheme=z.object({
    input:z.number().describe("Id of the account to join"),
});
const __lazy__invokeTmpChangeAccountFnFunctionArgsScheme=z.object({
});
export const invokeTmpChangeAccountFnFunctionArgsScheme:(typeof __base__invokeTmpChangeAccountFnFunctionArgsScheme)=__base__invokeTmpChangeAccountFnFunctionArgsScheme.merge(__lazy__invokeTmpChangeAccountFnFunctionArgsScheme) as any;
