/* <ALLOW_AUTO_DELETE DEPENDENCIES="TopPerformerType" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "flows",
    "messages",
    "segments"
] as const;
Object.freeze(unionAry);

export type TopPerformerType=typeof unionAry[number];

export const allTopPerformerTypeAry:TopPerformerType[]=unionAry as any;
