/* <ALLOW_AUTO_DELETE DEPENDENCIES="TriggerAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AutomationManualTriggerScheme } from './AutomationManualTriggerScheme';

const __base__invokeTriggerAutomationFnFunctionArgsScheme=z.object({
});
const __lazy__invokeTriggerAutomationFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>AutomationManualTriggerScheme),
});
export const invokeTriggerAutomationFnFunctionArgsScheme:(typeof __base__invokeTriggerAutomationFnFunctionArgsScheme)=__base__invokeTriggerAutomationFnFunctionArgsScheme.merge(__lazy__invokeTriggerAutomationFnFunctionArgsScheme) as any;
