/* <ALLOW_AUTO_DELETE DEPENDENCIES="UiEventType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

export const UiEventTypeScheme=z.enum([
    "click",
    "mouseDown",
    "mouseUp",
]);
