/* <ALLOW_AUTO_DELETE DEPENDENCIES="UiEventType" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export type UiEventType=(
    "click"|
    "mouseDown"|
    "mouseUp"
);
