/* <ALLOW_AUTO_DELETE DEPENDENCIES="UiEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { UiTargetScheme } from './UiTargetScheme';
import { UiEventTypeScheme } from './UiEventTypeScheme';

const __base__UiEventScheme=z.object({
    time:z.number(),
    tags:z.string().max(255).array().optional(),
});
const __lazy__UiEventScheme=z.object({
    type:z.lazy(()=>UiEventTypeScheme),
    target:z.lazy(()=>UiTargetScheme),
});
export const UiEventScheme:(typeof __base__UiEventScheme)=__base__UiEventScheme.merge(__lazy__UiEventScheme) as any;
