/* <ALLOW_AUTO_DELETE DEPENDENCIES="UiTarget" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

export interface UiTarget
{
    text?:string;
    className?:string;
    elem?:string;
}
