/* <ALLOW_AUTO_DELETE DEPENDENCIES="UiTarget" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__UiTargetScheme=z.object({
    text:z.string().max(255).optional(),
    className:z.string().max(255).optional(),
    elem:z.string().max(255).optional(),
});
const __lazy__UiTargetScheme=z.object({
});
export const UiTargetScheme:(typeof __base__UiTargetScheme)=__base__UiTargetScheme.merge(__lazy__UiTargetScheme) as any;
