/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearchColor" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "blackAndWhite",
    "black",
    "white",
    "yellow",
    "orange",
    "red",
    "purple",
    "magenta",
    "green",
    "teal",
    "blue"
] as const;
Object.freeze(unionAry);

export type UnsplashSearchColor=typeof unionAry[number];

export const allUnsplashSearchColorAry:UnsplashSearchColor[]=unionAry as any;
