/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearchFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { UnsplashSearchScheme } from './UnsplashSearchScheme';

const __base__invokeUnsplashSearchFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUnsplashSearchFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>UnsplashSearchScheme),
});
export const invokeUnsplashSearchFnFunctionArgsScheme:(typeof __base__invokeUnsplashSearchFnFunctionArgsScheme)=__base__invokeUnsplashSearchFnFunctionArgsScheme.merge(__lazy__invokeUnsplashSearchFnFunctionArgsScheme) as any;
