/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearchColor" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const UnsplashSearchColorScheme=z.enum([
    "blackAndWhite",
    "black",
    "white",
    "yellow",
    "orange",
    "red",
    "purple",
    "magenta",
    "green",
    "teal",
    "blue",
]);
