/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearch" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { UnsplashOrientation } from './UnsplashOrientation';
import type { UnsplashSearchColor } from './UnsplashSearchColor';

export interface UnsplashSearch
{
    query:string;
    /**
     * Count per page
     */
    count?:number;
    pageIndex?:number;
    color?:UnsplashSearchColor;
    orientation?:UnsplashOrientation;
}
