/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearch" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { UnsplashOrientationScheme } from './UnsplashOrientationScheme';
import { UnsplashSearchColorScheme } from './UnsplashSearchColorScheme';

const __base__UnsplashSearchScheme=z.object({
    query:z.string().max(255),
    count:z.number().optional().describe("Count per page"),
    pageIndex:z.number().optional(),
});
const __lazy__UnsplashSearchScheme=z.object({
    color:z.lazy(()=>UnsplashSearchColorScheme).optional(),
    orientation:z.lazy(()=>UnsplashOrientationScheme).optional(),
});
export const UnsplashSearchScheme:(typeof __base__UnsplashSearchScheme)=__base__UnsplashSearchScheme.merge(__lazy__UnsplashSearchScheme) as any;
