/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashSearchFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { UnsplashSearch } from './UnsplashSearch';

export interface invokeUnsplashSearchFnFunctionArgs
{
    input:UnsplashSearch;
}
