/* <ALLOW_AUTO_DELETE DEPENDENCIES="UnsplashOrientation" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

const unionAry=[
    "landscape",
    "portrait",
    "squarish"
] as const;
Object.freeze(unionAry);

export type UnsplashOrientation=typeof unionAry[number];

export const allUnsplashOrientationAry:UnsplashOrientation[]=unionAry as any;
