/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { Automation } from './Automation';

export interface invokeUpdateAutomationFnFunctionArgs
{
    input:Automation;
}
