/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateUserRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface UpdateUserRequest
{
    id:number;
    name?:string;
    email?:string;
    phone?:string;
    roles?:string[];
    allowMarketingComms?:boolean;
    demoRequestedAt?:number;
    demoCompletedAt?:number;
    platformUsages?:string[];
    websiteUrl?:string;
    enableNewUserNotifications?:boolean;
    enableScheduledAutomationNotifications?:boolean;
    enableNewSegmentNotifications?:boolean;
    enableNewMessageTemplateNotifications?:boolean;
    enableNewAutomationNotifications?:boolean;
    enableNewIntegrationNotifications?:boolean;
    enablePlatformUpdateNotifications?:boolean;
}
