/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateUserRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__UpdateUserRequestScheme=z.object({
    id:z.number().int(),
    name:z.string().max(255).optional(),
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
    roles:z.string().max(255).array().optional(),
    allowMarketingComms:z.boolean().optional(),
    demoRequestedAt:z.number().optional(),
    demoCompletedAt:z.number().optional(),
    platformUsages:z.string().max(255).array().optional(),
    websiteUrl:z.string().optional(),
    enableNewUserNotifications:z.boolean().optional(),
    enableScheduledAutomationNotifications:z.boolean().optional(),
    enableNewSegmentNotifications:z.boolean().optional(),
    enableNewMessageTemplateNotifications:z.boolean().optional(),
    enableNewAutomationNotifications:z.boolean().optional(),
    enableNewIntegrationNotifications:z.boolean().optional(),
    enablePlatformUpdateNotifications:z.boolean().optional(),
});
const __lazy__UpdateUserRequestScheme=z.object({
});
export const UpdateUserRequestScheme:(typeof __base__UpdateUserRequestScheme)=__base__UpdateUserRequestScheme.merge(__lazy__UpdateUserRequestScheme) as any;
