/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateProfileFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface invokeUpdateProfileFnFunctionArgs
{
    /**
     * Actual type is Partial Profile.
     * any is used as a workaround
     */
    input:any;
}
