/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateUserFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { UpdateUserRequest } from './UpdateUserRequest';

export interface invokeUpdateUserFnFunctionArgs
{
    input:UpdateUserRequest;
}
