/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateDomainRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface UpdateDomainRequest
{
    id:number;
    /**
     * Enables analytics and allows events
     * from the domain to be received and
     * processed by the account.
     */
    eventsCollectionEnabled?:boolean;
    emailSendingEnabled?:boolean;
    emailSendingSubdomain?:string;
    emailSendingVerified?:boolean;
}
