/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateProfilesFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeUpdateProfilesFnFunctionArgsScheme=z.object({
    input:z.any(),
});
const __lazy__invokeUpdateProfilesFnFunctionArgsScheme=z.object({
});
export const invokeUpdateProfilesFnFunctionArgsScheme:(typeof __base__invokeUpdateProfilesFnFunctionArgsScheme)=__base__invokeUpdateProfilesFnFunctionArgsScheme.merge(__lazy__invokeUpdateProfilesFnFunctionArgsScheme) as any;
