/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { AccountUpdateRequest } from './AccountUpdateRequest';

export interface invokeUpdateAccountFnFunctionArgs
{
    input:AccountUpdateRequest;
}
