/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateAccountFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AccountUpdateRequestScheme } from './AccountUpdateRequestScheme';

const __base__invokeUpdateAccountFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUpdateAccountFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>AccountUpdateRequestScheme),
});
export const invokeUpdateAccountFnFunctionArgsScheme:(typeof __base__invokeUpdateAccountFnFunctionArgsScheme)=__base__invokeUpdateAccountFnFunctionArgsScheme.merge(__lazy__invokeUpdateAccountFnFunctionArgsScheme) as any;
