/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateProfileFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeUpdateProfileFnFunctionArgsScheme=z.object({
    input:z.any().describe("Actual type is Partial Profile.\nany is used as a workaround"),
});
const __lazy__invokeUpdateProfileFnFunctionArgsScheme=z.object({
});
export const invokeUpdateProfileFnFunctionArgsScheme:(typeof __base__invokeUpdateProfileFnFunctionArgsScheme)=__base__invokeUpdateProfileFnFunctionArgsScheme.merge(__lazy__invokeUpdateProfileFnFunctionArgsScheme) as any;
