/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ProfileGroupScheme } from './ProfileGroupScheme';

const __base__invokeUpdateProfileGroupFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUpdateProfileGroupFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>ProfileGroupScheme),
});
export const invokeUpdateProfileGroupFnFunctionArgsScheme:(typeof __base__invokeUpdateProfileGroupFnFunctionArgsScheme)=__base__invokeUpdateProfileGroupFnFunctionArgsScheme.merge(__lazy__invokeUpdateProfileGroupFnFunctionArgsScheme) as any;
