/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateCustomFieldFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { CustomFieldScheme } from './CustomFieldScheme';

const __base__invokeUpdateCustomFieldFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUpdateCustomFieldFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>CustomFieldScheme),
});
export const invokeUpdateCustomFieldFnFunctionArgsScheme:(typeof __base__invokeUpdateCustomFieldFnFunctionArgsScheme)=__base__invokeUpdateCustomFieldFnFunctionArgsScheme.merge(__lazy__invokeUpdateCustomFieldFnFunctionArgsScheme) as any;
