/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateDomainFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { UpdateDomainRequest } from './UpdateDomainRequest';

export interface invokeUpdateDomainFnFunctionArgs
{
    input:UpdateDomainRequest;
}
