/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateProfileGroupFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ProfileGroup } from './ProfileGroup';

export interface invokeUpdateProfileGroupFnFunctionArgs
{
    input:ProfileGroup;
}
