/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateAutomationFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { AutomationScheme } from './AutomationScheme';

const __base__invokeUpdateAutomationFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUpdateAutomationFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>AutomationScheme),
});
export const invokeUpdateAutomationFnFunctionArgsScheme:(typeof __base__invokeUpdateAutomationFnFunctionArgsScheme)=__base__invokeUpdateAutomationFnFunctionArgsScheme.merge(__lazy__invokeUpdateAutomationFnFunctionArgsScheme) as any;
