/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateDomainRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__UpdateDomainRequestScheme=z.object({
    id:z.number().int(),
    eventsCollectionEnabled:z.boolean().optional().describe("Enables analytics and allows events from the domain to be received and processed by the account."),
    emailSendingEnabled:z.boolean().optional(),
    emailSendingSubdomain:z.string().max(255).optional(),
    emailSendingVerified:z.boolean().optional(),
});
const __lazy__UpdateDomainRequestScheme=z.object({
});
export const UpdateDomainRequestScheme:(typeof __base__UpdateDomainRequestScheme)=__base__UpdateDomainRequestScheme.merge(__lazy__UpdateDomainRequestScheme) as any;
