/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateUserFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { UpdateUserRequestScheme } from './UpdateUserRequestScheme';

const __base__invokeUpdateUserFnFunctionArgsScheme=z.object({
});
const __lazy__invokeUpdateUserFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>UpdateUserRequestScheme),
});
export const invokeUpdateUserFnFunctionArgsScheme:(typeof __base__invokeUpdateUserFnFunctionArgsScheme)=__base__invokeUpdateUserFnFunctionArgsScheme.merge(__lazy__invokeUpdateUserFnFunctionArgsScheme) as any;
