/* <ALLOW_AUTO_DELETE DEPENDENCIES="UpdateCustomFieldFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { CustomField } from './CustomField';

export interface invokeUpdateCustomFieldFnFunctionArgs
{
    input:CustomField;
}
