/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserPreSignUpFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Verifies a user can signup using
 * by comparing the users email to
 * records in the UserRegistrationCondition
 * table
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface invokeUserPreSignUpFnFunctionArgs
{
}
