/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserPreSignUpFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__invokeUserPreSignUpFnFunctionArgsScheme=z.object({
}).describe("Verifies a user can signup using by comparing the users email to records in the UserRegistrationCondition table");
const __lazy__invokeUserPreSignUpFnFunctionArgsScheme=z.object({
});
export const invokeUserPreSignUpFnFunctionArgsScheme:(typeof __base__invokeUserPreSignUpFnFunctionArgsScheme)=__base__invokeUserPreSignUpFnFunctionArgsScheme.merge(__lazy__invokeUserPreSignUpFnFunctionArgsScheme) as any;
