/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserUiEvent" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { UiEvent } from './UiEvent';
import { Profile } from './Profile';

export interface UserUiEvent
{
    profile:Profile;
    uiEvent:UiEvent;
}
