/* <ALLOW_AUTO_DELETE DEPENDENCIES="User" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { FormSubmission } from './FormSubmission';
import type { FileRecord } from './FileRecord';
import type { MessageRecord } from './MessageRecord';
import type { NotificationDevice } from './NotificationDevice';
import type { UserActivityLogEntry } from './UserActivityLogEntry';

/**
 * A user within an organization
 */
export interface User
{
    id:number;
    created?:number;
    name?:string;
    firstName?:string;
    lastName?:string;
    email?:string;
    phone?:string;
    accountId?:number;
    roles:string[];
    cognitoUserId?:string;
    /**
     * If true the user would like to receive marketing
     * communications, including emails and sms.
     */
    allowMarketingComms?:boolean;
    /**
     * The time at which the user requested a demo
     */
    demoRequestedAt?:number;
    demoCompletedAt?:number;
    websiteUrl?:string;
    enableNewUserNotifications?:boolean;
    enableScheduledAutomationNotifications?:boolean;
    enableNewSegmentNotifications?:boolean;
    enableNewMessageTemplateNotifications?:boolean;
    enableNewAutomationNotifications?:boolean;
    enableNewIntegrationNotifications?:boolean;
    enablePlatformUpdateNotifications?:boolean;
    activity?:UserActivityLogEntry[];
    notificationDevices?:NotificationDevice[];
    messages?:MessageRecord[];
    files?:FileRecord[];
    formSubmissions?:FormSubmission[];
}
