/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserRegistrationCondition" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface UserRegistrationCondition
{
    id:number;
    allow:boolean;
    domain?:string;
    email?:string;
}
