/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserActivityLogEntry" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

/**
 * Used to track the actions of organization
 * users.
 */
export interface UserActivityLogEntry
{
    id:number;
    userId?:number;
}
