/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserRegistrationCondition" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__UserRegistrationConditionScheme=z.object({
    id:z.number().int(),
    allow:z.boolean(),
    domain:z.string().optional(),
    email:z.string().email().optional(),
});
const __lazy__UserRegistrationConditionScheme=z.object({
});
export const UserRegistrationConditionScheme:(typeof __base__UserRegistrationConditionScheme)=__base__UserRegistrationConditionScheme.merge(__lazy__UserRegistrationConditionScheme) as any;
