/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserActivityLogEntry" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__UserActivityLogEntryScheme=z.object({
    id:z.number().int(),
    userId:z.number().int().optional(),
}).describe("Used to track the actions of organization users.");
const __lazy__UserActivityLogEntryScheme=z.object({
});
export const UserActivityLogEntryScheme:(typeof __base__UserActivityLogEntryScheme)=__base__UserActivityLogEntryScheme.merge(__lazy__UserActivityLogEntryScheme) as any;
