/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserAccessToken" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { ResourceAccessToken } from './ResourceAccessToken';

/**
 * Stores calculated information about
 * the resources a user has access to.
 */
export interface UserAccessToken
{
    userId?:string;
    userIntId?:number;
    accountId?:number;
    roles:string[];
    clams:Record<string,string>;
    isAdmin:boolean;
    resources:ResourceAccessToken[];
}
