/* <ALLOW_AUTO_DELETE DEPENDENCIES="UserAccessToken" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { ResourceAccessTokenScheme } from './ResourceAccessTokenScheme';

const __base__UserAccessTokenScheme=z.object({
    userId:z.string().max(255).optional(),
    userIntId:z.number().int().optional(),
    accountId:z.number().int().optional(),
    roles:z.string().max(255).array(),
    clams:z.record(z.string()),
    isAdmin:z.boolean(),
}).describe("Stores calculated information about the resources a user has access to.");
const __lazy__UserAccessTokenScheme=z.object({
    resources:z.lazy(()=>ResourceAccessTokenScheme).array(),
});
export const UserAccessTokenScheme:(typeof __base__UserAccessTokenScheme)=__base__UserAccessTokenScheme.merge(__lazy__UserAccessTokenScheme) as any;
