/* <ALLOW_AUTO_DELETE DEPENDENCIES="User" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';
import { MessageTargetScheme } from './MessageTargetScheme';
import { NotificationDeviceScheme } from './NotificationDeviceScheme';
import { UserActivityLogEntryScheme } from './UserActivityLogEntryScheme';

const __base__UserScheme=z.object({
    id:z.number().int(),
    name:z.string().max(255).optional(),
    email:z.string().email().optional(),
    phone:z.string().max(255).optional(),
    accountId:z.number().int(),
    roles:z.string().max(255).array(),
}).describe("A user within an organization");
const __lazy__UserScheme=z.object({
    activity:z.lazy(()=>UserActivityLogEntryScheme).array(),
    notificationDevices:z.lazy(()=>NotificationDeviceScheme).array().optional(),
    targetedMessages:z.lazy(()=>MessageTargetScheme).array().optional(),
});
export const UserScheme:(typeof __base__UserScheme)=__base__UserScheme.merge(__lazy__UserScheme) as any;
