/* <ALLOW_AUTO_DELETE DEPENDENCIES="UtmParams" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

export const UtmParamsScheme=z.object({
    utmCampaign:z.string().max(255).optional().describe("Campaign name. example - summer-sales or fall-discounts"),
    utmSource:z.string().max(255).optional().describe("Where traffic is coming from for example - google or facebook"),
    utmMedium:z.string().max(255).optional().describe("What type of medium traffic is coming from.\nexample - sms, email, social, search"),
    utmContent:z.string().max(255).optional().describe("What type of content was interacted with.\nexample - image, nav-link, menu-link"),
    utmTerm:z.string().max(255).optional().describe("The copy the generated traffic. This will often be the tag line of an ad.- $layout: 1601 3809 300"),
});
