/* <ALLOW_AUTO_DELETE DEPENDENCIES="UtmParams" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface UtmParams
{
    /**
     * Campaign name. example - summer-sales or fall-discounts
     */
    utmCampaign?:string;
    /**
     * Where traffic is coming from for example - google or facebook
     */
    utmSource?:string;
    /**
     * What type of medium traffic is coming from.
     * example - sms, email, social, search
     */
    utmMedium?:string;
    /**
     * What type of content was interacted with.
     * example - image, nav-link, menu-link
     */
    utmContent?:string;
    /**
     * The copy the generated traffic. This will often be the tag
     * line of an ad.- $layout: 1601 3809 300
     */
    utmTerm?:string;
}
