/* <ALLOW_AUTO_DELETE DEPENDENCIES="VerifyEmailRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';

const __base__VerifyEmailRequestScheme=z.object({
    email:z.string().email(),
    code:z.string().max(255),
});
const __lazy__VerifyEmailRequestScheme=z.object({
});
export const VerifyEmailRequestScheme:(typeof __base__VerifyEmailRequestScheme)=__base__VerifyEmailRequestScheme.merge(__lazy__VerifyEmailRequestScheme) as any;
