/* <ALLOW_AUTO_DELETE DEPENDENCIES="VerifyEmailRequest" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen

export interface VerifyEmailRequest
{
    email:string;
    code:string;
}
