/* <ALLOW_AUTO_DELETE DEPENDENCIES="VerifyEmailFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import type { VerifyEmailRequest } from './VerifyEmailRequest';

export interface invokeVerifyEmailFnFunctionArgs
{
    input:VerifyEmailRequest;
}
