/* <ALLOW_AUTO_DELETE DEPENDENCIES="VerifyEmailFn" /> */
// this file was auto generated by @iyio/protogen - https://github.com/iyioio/common/tree/main/packages/protogen
import { z } from 'zod';
import { VerifyEmailRequestScheme } from './VerifyEmailRequestScheme';

const __base__invokeVerifyEmailFnFunctionArgsScheme=z.object({
});
const __lazy__invokeVerifyEmailFnFunctionArgsScheme=z.object({
    input:z.lazy(()=>VerifyEmailRequestScheme),
});
export const invokeVerifyEmailFnFunctionArgsScheme:(typeof __base__invokeVerifyEmailFnFunctionArgsScheme)=__base__invokeVerifyEmailFnFunctionArgsScheme.merge(__lazy__invokeVerifyEmailFnFunctionArgsScheme) as any;
