/* <ALLOW_AUTO_DELETE DEPENDENCIES="Worker" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen
import { z } from 'zod';

const __base__WorkerScheme=z.object({
    id:z.number().int().describe("A combination of the workers userId and nodeAddress.\nformat = {userId}.{nodeAddress}"),
    uv:z.number().int(),
    created:z.number(),
    data:z.record(z.string()).optional(),
}).describe("todo - change format of id. right now the structure of the id only allows for a users to a a single worker at a node address");
const __lazy__WorkerScheme=z.object({
});
export const WorkerScheme:(typeof __base__WorkerScheme)=__base__WorkerScheme.merge(__lazy__WorkerScheme) as any;
