/* <ALLOW_AUTO_DELETE DEPENDENCIES="Worker" /> */
// this file was autogenerated by @iyio/protogen - https://github.com/iyioio/common/packages/protogen

/**
 * todo - change format of id. right now
 * the structure of the id only allows
 * for a users to a a single worker at
 * a node address
 */
export interface Worker
{
    /**
     * A combination of the workers userId
     * and nodeAddress.
     * format = {userId}.{nodeAddress}
     */
    id:number;
    uv:number;
    created:number;
    data?:Record<string,string>;
}
