export const industries: string[] = [
    "Agriculture and Food Services",
    "Architecture and Construction",
    "Arts and Artists",
    "Beauty and Personal Care",
    "Business and Finance",
    "Computers and Electronics",
    "Construction",
    "Consulting",
    "Creative Services/Agency",
    "Daily Deals/E-Coupons",
    "E-Commerce",
    "Education and Training",
    "Entertainment and Events",
    "Gambling",
    "Games",
    "Government",
    "Health and Fitness",
    "Hobbies",
    "Home and Garden",
    "Insurance",
    "Legal",
    "Manufacturing",
    "Marketing and Advertising",
    "Media and Publishing",
    "Medical, Dental, and Healthcare",
    "Mobile",
    "Music and Musicians",
    "Non-Profit",
    "Pharmaceuticals",
    "Photo and Video",
    "Politics",
    "Professional Services",
    "Public Relations",
    "Real Estate",
    "Recruitment and Staffing",
    "Religion",
    "Restaurant",
    "Restaurant and Venue",
    "Retail",
    "Social Networks and Online Communities",
    "Software and Web App",
    "Sports",
    "Telecommunications",
    "Travel and Transportation",
    "Vitamin Supplements",
    "Other"
];

export const getDefaultIndustry=()=>{
    //logic
    return industries[0];
}