
import { UiActionItem, UiActionSubItem } from "@iyio/common";
import { IconType } from "./icon-types";

export const portalNavItems: UiActionSubItem<IconType>[] = [
    // {
    //     icon:'chart-tree-map',
    //     title:'Insights',
    //     to:'/insights'
    // },
    {
        icon: 'house',
        title: 'Home',
        to: '/',
        description: 'Displays links to common areas in the platform',
    },
    {
        icon: 'chart-mixed',
        title: 'Analytics',
        sub: [
            {
                title: 'Web Activity',
                to: '/analytics/web-activity',
                description:
                    'Displays analytics about web activity generated by users using your websites and apps',
            },
            {
                title: 'Deliverability',
                to: '/analytics/deliverability',
                description:
                    'Displays analytics about email, sms and notification deliveries',
            },
            {
                title: 'Commerce',
                to: '/analytics/comms',
                description:
                    'Displays analytics about e-commerce such as total revenue and other e-commerce related information',
            },
            {
                title: 'Attribution',
                to: '/analytics/attribution',
                description:
                    'Display analytics about communication channel attribution',
            },
            // @hidden
            {
                title: 'Reports',
                to: '/analytics/reports',
                description:
                    'Displays analytics about web activity generated by users using your websites and apps',
            },
            {
                title: 'All Events',
                to: '/analytics/events',
                description: 'A table of all generated events',
            },
        ],
    },
    {
        icon: 'bookmark',
        title: 'Research',
        to: '/research',
    },
    {
        icon: 'user-circle',
        title: 'Customers',
        sub: [
            {
                icon: 'user-circle',
                title: 'Profiles',
                to: '/profiles',
                description: 'Displays all tracked customer profiles',
            },
            {
                icon: 'bullseye-arrow',
                title: 'Segments',
                to: '/segments',
                description:
                    'Displays all customer profile segments. A customer profile segment is a grouping of customer profiles based on user defined conditions. Customer profile segments are used to target groups of customer profiles for various marketing purposes',
            },
            {
                title: 'Lists',
                to: '/lists',
                description: 'Displays a imported lists of customer profiles',
            },
        ],
    },
    {
        icon: 'file-lines',
        title: 'Forms',
        to: '/forms',
        description: 'Custom forms that can be embedded into your website.',
    },
    {
        icon: 'message-lines',
        title: 'Messages',
        sub: [
            {
                title: 'Blocks',
                to: '/messages/blocks',
                description:
                    'Reuseable blocks that can be inserted into message templates',
            },
            {
                title: 'Templates',
                to: '/messages/email',
                description:
                    'Message templates for emails, sms and notifications',
            },
            // {
            //     title:'SMS',
            //     to:'/messages/always-on'
            // },
            // {
            //     title:'Notifications',
            //     to:'/messages/always-on'
            // },
            // {
            //     title:'Perennial'
            // }
        ],
    },
    // {
    //     icon:'badge-percent',
    //     title:'Rewards',
    // },

    {
        icon: 'gear',
        title: 'Automations',
        to: '/automations',
        description:
            'Build custom automations to communicate with customers. Currently disabled',
    },
];

export const portalNavItemsWithProfile:UiActionItem[]=[
    ...portalNavItems,
    {
        icon:'user-circle',
        title:'Profile',
        to:'/user-profile',
    }
]

export const accountSettingsNavItems:UiActionSubItem<IconType>[]=[
    {
        icon:'buildings',
        title:'Account',
        to:'/account'
    },
    {
        icon:'credit-card',
        title:'Billing',
        to:'/account/billing'
    },
    {
        icon:'web',
        title:'Domains',
        to:'/account/domains',
    },
    {
        icon:'binary',
        title:'Data',
        to:'/account/data'
    },
    {
        icon:'envelope',
        title:'Email',
        to:'/account/email'
    },
    // {
    //     icon:'messages',
    //     title:'SMS',
    //     to:'/account/sms'
    // },
    {
        icon:'bell',
        title:'Notifications',
        to:'/account/notifications'
    },

]

export const flatPortalNav=[...portalNavItems,...accountSettingsNavItems];
for(let i=0;i<flatPortalNav.length;i++){
    const item=flatPortalNav[i];
    if(!item?.sub){continue}

    const subs=item.sub.map(sub=>({
        ...sub,
        title:`${item.title} - ${sub.title}`
    }));
    flatPortalNav.splice(i,1,...subs);
    i+=subs.length-1;
}
